import { createHash } from "node:crypto";
import { Injectable } from "@nestjs/common";
import type { Datasource, DatasourceType } from "@text2sql/shared-types";
import { DomainError } from "../../../common/domain-error";
import { DatasourceRepository } from "../../platform/data/persistence";
import { QueryExecutorRouterService } from "../../platform/data/query";
import type { UpsertModelingSetupDto } from "./dto/upsert-modeling-setup.dto";
import { WorkspaceDatasourceService } from "./workspace-datasource.service";
import { WorkspaceRelationshipService } from "./workspace-relationship.service";

type Actor = {
  id: string;
  role: "admin" | "user";
  workspaceRoles?: Record<string, "admin" | "member">;
  isSystemAdmin?: boolean;
};

type ModelingSetupColumn = {
  name: string;
  dataType: string;
  isNullable: boolean;
  isPrimaryKey: boolean;
};

type ModelingSetupModel = {
  id: string;
  tableName: string;
  modelName: string;
  columns: ModelingSetupColumn[];
};

type ModelingRelationshipRecommendation = {
  id: string;
  name: string;
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
  confidence: number;
  reason: "foreign_key_constraint" | "fk_naming_suffix";
  isAutoGenerated: true;
  bridge: {
    left: {
      dataset: string;
      table: string;
      column: string;
    };
    right: {
      dataset: string;
      table: string;
      column: string;
    };
    operator: "eq";
    confidence: number;
  };
};

type ModelingSetupContext = {
  policyVersion: number;
  selectedTables: string[];
};

type ModelingSetupCommitResponse = {
  stage: "setup_commit_applied";
  workspaceId: string;
  datasourceId: string;
  policyVersion: number;
  selectedTables: string[];
  committedRelationshipIds: string[];
  committedRelationshipCount: number;
  draft: {
    revision: number;
    graphHash: string;
    edgeCount: number;
    updatedAt: string;
  };
  replayed: boolean;
};

type CommitIdempotencyRecord = {
  payloadHash: string;
  response: ModelingSetupCommitResponse;
  expiresAt: number;
};

type ForeignKeyConstraint = {
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
};

const MAX_IDEMPOTENCY_KEY_LENGTH = 128;
const IDEMPOTENCY_TTL_MS = 24 * 60 * 60 * 1000;

const normalizeTableName = (value: string): string => value.trim().toLowerCase();

@Injectable()
export class WorkspaceModelingService {
  private readonly commitIdempotencyStore = new Map<string, CommitIdempotencyRecord>();

  constructor(
    private readonly workspaceDatasourceService: WorkspaceDatasourceService,
    private readonly workspaceRelationshipService: WorkspaceRelationshipService,
    private readonly datasourceRepository: DatasourceRepository,
    private readonly queryExecutorRouter: QueryExecutorRouterService
  ) {}

  async listSetupTables(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string
  ): Promise<{
    stage: "table_selection_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    items: string[];
    discoveredTableCount: number;
    restrictedTableCount: number;
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");

    const [tableResult, permissionResult] = await Promise.all([
      this.workspaceDatasourceService.listDatasourceTables(actor, workspaceId, datasourceId),
      this.workspaceDatasourceService.listDatasourceTablePermissions(
        actor,
        workspaceId,
        datasourceId
      )
    ]);
    const discoveredSet = new Set(tableResult.items.map((item) => item.toLowerCase()));
    const allowedTables = permissionResult.tableNames
      .filter((tableName) => discoveredSet.has(tableName))
      .sort((left, right) => left.localeCompare(right));

    return {
      stage: "table_selection_ready",
      workspaceId,
      datasourceId,
      policyVersion: permissionResult.policyVersion,
      items: allowedTables,
      discoveredTableCount: tableResult.items.length,
      restrictedTableCount: Math.max(0, tableResult.items.length - allowedTables.length)
    };
  }

  async saveSelectedTables(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_tables_saved";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTableNames: string[];
    impactSummary: {
      beforeCount: number;
      afterCount: number;
      addedCount: number;
      removedCount: number;
      retainedCount: number;
    };
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveSetupContext(
      actor,
      workspaceId,
      datasourceId,
      body
    );

    return {
      stage: "setup_tables_saved",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      selectedTableNames: context.selectedTables,
      impactSummary: {
        beforeCount: context.selectedTables.length,
        afterCount: context.selectedTables.length,
        addedCount: context.selectedTables.length,
        removedCount: 0,
        retainedCount: context.selectedTables.length
      }
    };
  }

  async recommendSetupRelationships(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_relationship_recommendation_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTableNames: string[];
    suggestions: ModelingRelationshipRecommendation[];
    summary: {
      recommendationCount: number;
      modelCount: number;
      columnCount: number;
    };
  }> {
    const preview = await this.previewSetup(actor, workspaceIdRaw, datasourceIdRaw, body);
    return {
      stage: "setup_relationship_recommendation_ready",
      workspaceId: preview.workspaceId,
      datasourceId: preview.datasourceId,
      policyVersion: preview.policyVersion,
      selectedTableNames: preview.selectedTables,
      suggestions: preview.relationshipRecommendations,
      summary: {
        recommendationCount: preview.summary.recommendationCount,
        modelCount: preview.summary.modelCount,
        columnCount: preview.summary.columnCount
      }
    };
  }

  async previewSetup(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_preview_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTables: string[];
    models: ModelingSetupModel[];
    relationshipRecommendations: ModelingRelationshipRecommendation[];
    defaultSelectedRecommendationIds: string[];
    summary: {
      modelCount: number;
      columnCount: number;
      recommendationCount: number;
    };
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveSetupContext(
      actor,
      workspaceId,
      datasourceId,
      body
    );
    const datasource = await this.loadDatasourceOrThrow(datasourceId);
    const models = await this.introspectModels(datasource, context.selectedTables);
    const constraints = await this.discoverForeignKeyConstraints(
      datasource,
      context.selectedTables
    );
    const recommendations = this.recommendRelationships({
      datasourceId,
      models,
      constraints
    });

    return {
      stage: "setup_preview_ready",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      selectedTables: context.selectedTables,
      models,
      relationshipRecommendations: recommendations,
      defaultSelectedRecommendationIds: recommendations.map((item) => item.id),
      summary: {
        modelCount: models.length,
        columnCount: models.reduce((sum, model) => sum + model.columns.length, 0),
        recommendationCount: recommendations.length
      }
    };
  }

  async commitSetup(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto,
    idempotencyKeyRaw?: string
  ): Promise<ModelingSetupCommitResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const idempotencyKey = this.normalizeOptionalIdempotencyKey(idempotencyKeyRaw);
    const payloadHash = this.hashCommitPayload(body);
    const idempotencyScope = idempotencyKey
      ? this.buildCommitIdempotencyScope({
          actorId: actor.id,
          workspaceId,
          datasourceId,
          idempotencyKey
        })
      : undefined;
    if (idempotencyScope) {
      this.pruneCommitIdempotencyStore();
      const replayed = this.readCommitIdempotencyRecord({
        scope: idempotencyScope,
        payloadHash
      });
      if (replayed) {
        return replayed;
      }
    }

    const preview = await this.previewSetup(actor, workspaceId, datasourceId, body);
    const recommendationMap = new Map(
      preview.relationshipRecommendations.map((item) => [item.id, item])
    );
    const selectedRecommendationIds =
      body.selectedRecommendationIds === undefined
        ? preview.defaultSelectedRecommendationIds
        : body.selectedRecommendationIds;

    const missingRecommendationIds = selectedRecommendationIds.filter(
      (item) => !recommendationMap.has(item)
    );
    if (missingRecommendationIds.length > 0) {
      throw new DomainError(
        "WORKSPACE_MODELING_SETUP_RELATIONSHIP_NOT_FOUND",
        "提交的关系建议不存在于当前 setup 预览结果。",
        400,
        {
          missingRecommendationIds
        }
      );
    }

    const committedRecommendations = selectedRecommendationIds
      .map((item) => recommendationMap.get(item)!)
      .sort((left, right) => left.id.localeCompare(right.id));
    const replaced = await this.workspaceRelationshipService.replaceDraft(
      actor,
      workspaceId,
      datasourceId,
      {
        policyVersion: preview.policyVersion,
        edges: committedRecommendations.map((item) => ({
          id: item.id,
          name: item.name,
          bridge: item.bridge
        }))
      }
    );

    const response: ModelingSetupCommitResponse = {
      stage: "setup_commit_applied",
      workspaceId,
      datasourceId,
      policyVersion: preview.policyVersion,
      selectedTables: preview.selectedTables,
      committedRelationshipIds: committedRecommendations.map((item) => item.id),
      committedRelationshipCount: committedRecommendations.length,
      draft: {
        revision: replaced.draft.revision,
        graphHash: replaced.draft.graphHash,
        edgeCount: replaced.draft.edges.length,
        updatedAt: replaced.draft.updatedAt
      },
      replayed: false
    };

    if (idempotencyScope) {
      this.commitIdempotencyStore.set(idempotencyScope, {
        payloadHash,
        response,
        expiresAt: Date.now() + IDEMPOTENCY_TTL_MS
      });
    }

    return response;
  }

  private async resolveSetupContext(
    actor: Actor,
    workspaceId: string,
    datasourceId: string,
    body: UpsertModelingSetupDto
  ): Promise<ModelingSetupContext> {
    const [tableResult, permissionResult] = await Promise.all([
      this.workspaceDatasourceService.listDatasourceTables(actor, workspaceId, datasourceId),
      this.workspaceDatasourceService.listDatasourceTablePermissions(
        actor,
        workspaceId,
        datasourceId
      )
    ]);

    if (
      body.policyVersion !== undefined &&
      permissionResult.policyVersion !== body.policyVersion
    ) {
      throw new DomainError(
        "WORKSPACE_DATASOURCE_POLICY_VERSION_CONFLICT",
        "policyVersion 已过期，请刷新后重试。",
        409,
        {
          workspaceId,
          datasourceId,
          expectedPolicyVersion: permissionResult.policyVersion,
          providedPolicyVersion: body.policyVersion
        }
      );
    }

    const discoveredSet = new Set(tableResult.items.map((item) => item.toLowerCase()));
    const allowedSet = new Set(
      permissionResult.tableNames.filter((tableName) => discoveredSet.has(tableName))
    );
    const selectedTables = Array.from(
      new Set(body.selectedTables.map((tableName) => normalizeTableName(tableName)))
    );
    const forbiddenTables = selectedTables.filter((tableName) => !allowedSet.has(tableName));
    if (forbiddenTables.length > 0) {
      throw new DomainError(
        "WORKSPACE_MODELING_SETUP_TABLE_FORBIDDEN",
        "选中的表包含未授权或不存在表。",
        403,
        {
          workspaceId,
          datasourceId,
          forbiddenTables
        }
      );
    }

    return {
      policyVersion: permissionResult.policyVersion,
      selectedTables: selectedTables.sort((left, right) => left.localeCompare(right))
    };
  }

  private async loadDatasourceOrThrow(datasourceId: string): Promise<Datasource> {
    const datasource = await this.datasourceRepository.getDatasourceById(datasourceId, {
      includeDeleted: true
    });
    if (!datasource || datasource.status === "deleted") {
      throw new DomainError("DATASOURCE_NOT_FOUND", "数据源不存在或已删除。", 404, {
        datasourceId
      });
    }
    return datasource;
  }

  private async introspectModels(
    datasource: Datasource,
    selectedTables: string[]
  ): Promise<ModelingSetupModel[]> {
    const models: ModelingSetupModel[] = [];
    for (const tableName of selectedTables) {
      const queryResult = await this.queryExecutorRouter.execute({
        datasource,
        sql: this.buildColumnDiscoverySql(datasource.type, tableName),
        limit: 200
      });
      const columns = queryResult.rows
        .map((row) => this.readColumnDefinition(row))
        .filter((item): item is ModelingSetupColumn => Boolean(item))
        .sort((left, right) => left.name.localeCompare(right.name));
      models.push({
        id: tableName,
        tableName,
        modelName: this.toModelName(tableName),
        columns
      });
    }
    return models.sort((left, right) => left.tableName.localeCompare(right.tableName));
  }

  private readColumnDefinition(row: Record<string, unknown>): ModelingSetupColumn | null {
    const name = this.readString(row, [
      "columnName",
      "column_name",
      "name",
      "field",
      "COLUMN_NAME"
    ]);
    if (!name) {
      return null;
    }
    const dataType =
      this.readString(row, ["dataType", "data_type", "type", "DATA_TYPE"]) ??
      "unknown";
    const isPrimaryKey =
      this.readBooleanLike(row["isPrimaryKey"]) ||
      this.readBooleanLike(row["primaryKey"]) ||
      this.readBooleanLike(row["pk"]) ||
      this.readString(row, ["columnKey", "column_key"])?.toUpperCase() === "PRI" ||
      this.readString(row, ["constraintType", "constraint_type"]) === "PRIMARY KEY";
    const isNullableRaw =
      this.readBooleanLike(row["isNullable"]) ??
      this.readBooleanLike(row["nullable"]) ??
      this.readBooleanLike(row["is_nullable"]);
    const notNullRaw =
      this.readBooleanLike(row["notnull"]) ??
      this.readBooleanLike(row["notNull"]) ??
      this.readBooleanLike(row["not_null"]);
    const isNullable = isNullableRaw ?? !(notNullRaw ?? false);

    return {
      name: name.toLowerCase(),
      dataType: dataType.toLowerCase(),
      isNullable,
      isPrimaryKey
    };
  }

  private async discoverForeignKeyConstraints(
    datasource: Datasource,
    selectedTables: string[]
  ): Promise<ForeignKeyConstraint[]> {
    const selectedSet = new Set(selectedTables);
    if (selectedTables.length === 0) {
      return [];
    }
    if (datasource.type === "sqlite" || datasource.type === "csv" || datasource.type === "excel") {
      const constraints: ForeignKeyConstraint[] = [];
      for (const tableName of selectedTables) {
        const result = await this.queryExecutorRouter.execute({
          datasource,
          sql: `
SELECT "table" AS targetTable, "from" AS sourceColumn, COALESCE(NULLIF("to", ''), 'id') AS targetColumn
FROM pragma_foreign_key_list('${this.escapeSqlLiteral(tableName)}')
ORDER BY id, seq
          `.trim(),
          limit: 200
        });
        for (const row of result.rows) {
          const targetTable = this.readString(row, ["targetTable", "table"]);
          const sourceColumn = this.readString(row, ["sourceColumn", "from"]);
          const targetColumn = this.readString(row, ["targetColumn", "to"]);
          if (!targetTable || !sourceColumn || !targetColumn) {
            continue;
          }
          const normalizedTargetTable = normalizeTableName(targetTable);
          if (!selectedSet.has(normalizedTargetTable)) {
            continue;
          }
          constraints.push({
            sourceTable: tableName,
            sourceColumn: normalizeTableName(sourceColumn),
            targetTable: normalizedTargetTable,
            targetColumn: normalizeTableName(targetColumn)
          });
        }
      }
      return constraints.sort((left, right) =>
        `${left.sourceTable}.${left.sourceColumn}.${left.targetTable}.${left.targetColumn}`.localeCompare(
          `${right.sourceTable}.${right.sourceColumn}.${right.targetTable}.${right.targetColumn}`
        )
      );
    }

    const inClause = selectedTables
      .map((tableName) => `'${this.escapeSqlLiteral(tableName)}'`)
      .join(", ");
    const sql =
      datasource.type === "mysql"
        ? `
SELECT
  table_name AS sourceTable,
  column_name AS sourceColumn,
  referenced_table_name AS targetTable,
  referenced_column_name AS targetColumn
FROM information_schema.key_column_usage
WHERE table_schema = DATABASE()
  AND referenced_table_name IS NOT NULL
  AND table_name IN (${inClause})
  AND referenced_table_name IN (${inClause})
ORDER BY table_name, column_name, referenced_table_name, referenced_column_name
          `.trim()
        : `
SELECT
  kcu.table_name AS sourceTable,
  kcu.column_name AS sourceColumn,
  ccu.table_name AS targetTable,
  ccu.column_name AS targetColumn
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name
  AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage ccu
  ON ccu.constraint_name = tc.constraint_name
  AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
  AND kcu.table_name IN (${inClause})
  AND ccu.table_name IN (${inClause})
ORDER BY kcu.table_name, kcu.column_name, ccu.table_name, ccu.column_name
          `.trim();
    const result = await this.queryExecutorRouter.execute({
      datasource,
      sql,
      limit: 200
    });

    return result.rows
      .map((row) => {
        const sourceTable = this.readString(row, ["sourceTable", "source_table"]);
        const sourceColumn = this.readString(row, ["sourceColumn", "source_column"]);
        const targetTable = this.readString(row, ["targetTable", "target_table"]);
        const targetColumn = this.readString(row, ["targetColumn", "target_column"]);
        if (!sourceTable || !sourceColumn || !targetTable || !targetColumn) {
          return null;
        }
        const normalizedSourceTable = normalizeTableName(sourceTable);
        const normalizedTargetTable = normalizeTableName(targetTable);
        if (!selectedSet.has(normalizedSourceTable) || !selectedSet.has(normalizedTargetTable)) {
          return null;
        }
        return {
          sourceTable: normalizedSourceTable,
          sourceColumn: normalizeTableName(sourceColumn),
          targetTable: normalizedTargetTable,
          targetColumn: normalizeTableName(targetColumn)
        };
      })
      .filter((item): item is ForeignKeyConstraint => Boolean(item));
  }

  private recommendRelationships(input: {
    datasourceId: string;
    models: ModelingSetupModel[];
    constraints: ForeignKeyConstraint[];
  }): ModelingRelationshipRecommendation[] {
    const modelMap = new Map(input.models.map((item) => [item.tableName, item]));
    const recommendationMap = new Map<string, ModelingRelationshipRecommendation>();

    for (const constraint of input.constraints) {
      const source = modelMap.get(constraint.sourceTable);
      const target = modelMap.get(constraint.targetTable);
      if (!source || !target) {
        continue;
      }
      const sourceColumn = source.columns.find(
        (column) => column.name === constraint.sourceColumn
      );
      const targetColumn = target.columns.find(
        (column) => column.name === constraint.targetColumn
      );
      if (!sourceColumn || !targetColumn) {
        continue;
      }
      const recommendation = this.buildRecommendation({
        datasourceId: input.datasourceId,
        sourceTable: source.tableName,
        sourceColumn: sourceColumn.name,
        targetTable: target.tableName,
        targetColumn: targetColumn.name,
        confidence: 0.99,
        reason: "foreign_key_constraint"
      });
      recommendationMap.set(this.recommendationSignature(recommendation), recommendation);
    }

    for (const sourceModel of input.models) {
      for (const column of sourceModel.columns) {
        const sourceColumn = column.name.toLowerCase();
        if (!sourceColumn.endsWith("_id") || sourceColumn === "id") {
          continue;
        }
        const stem = sourceColumn.slice(0, -3);
        const candidates = this.candidateParentTables(stem);
        for (const candidate of candidates) {
          if (candidate === sourceModel.tableName) {
            continue;
          }
          const targetModel = modelMap.get(candidate);
          if (!targetModel) {
            continue;
          }
          const targetColumn =
            targetModel.columns.find((item) => item.name === "id") ??
            targetModel.columns.find((item) => item.isPrimaryKey);
          if (!targetColumn) {
            continue;
          }
          const confidence = candidate === stem ? 0.94 : 0.86;
          const recommendation = this.buildRecommendation({
            datasourceId: input.datasourceId,
            sourceTable: sourceModel.tableName,
            sourceColumn,
            targetTable: targetModel.tableName,
            targetColumn: targetColumn.name,
            confidence,
            reason: "fk_naming_suffix"
          });
          const signature = this.recommendationSignature(recommendation);
          const existing = recommendationMap.get(signature);
          if (!existing || existing.confidence < recommendation.confidence) {
            recommendationMap.set(signature, recommendation);
          }
          break;
        }
      }
    }

    return Array.from(recommendationMap.values()).sort((left, right) => {
      if (left.confidence !== right.confidence) {
        return right.confidence - left.confidence;
      }
      return left.id.localeCompare(right.id);
    });
  }

  private buildRecommendation(input: {
    datasourceId: string;
    sourceTable: string;
    sourceColumn: string;
    targetTable: string;
    targetColumn: string;
    confidence: number;
    reason: "foreign_key_constraint" | "fk_naming_suffix";
  }): ModelingRelationshipRecommendation {
    const signature = `${input.sourceTable}.${input.sourceColumn}->${input.targetTable}.${input.targetColumn}`;
    const id = `rel_${createHash("sha1").update(signature).digest("hex").slice(0, 16)}`;
    const normalizedConfidence = Number(Math.max(0, Math.min(1, input.confidence)).toFixed(4));
    return {
      id,
      name: `${input.sourceTable}_to_${input.targetTable}`,
      sourceTable: input.sourceTable,
      sourceColumn: input.sourceColumn,
      targetTable: input.targetTable,
      targetColumn: input.targetColumn,
      confidence: normalizedConfidence,
      reason: input.reason,
      isAutoGenerated: true,
      bridge: {
        left: {
          dataset: input.datasourceId,
          table: input.sourceTable,
          column: input.sourceColumn
        },
        right: {
          dataset: input.datasourceId,
          table: input.targetTable,
          column: input.targetColumn
        },
        operator: "eq",
        confidence: normalizedConfidence
      }
    };
  }

  private candidateParentTables(stem: string): string[] {
    const normalized = stem.trim().toLowerCase();
    if (!normalized) {
      return [];
    }
    const candidates = new Set<string>([normalized]);
    if (normalized.endsWith("ies")) {
      candidates.add(`${normalized.slice(0, -3)}y`);
    } else if (normalized.endsWith("s")) {
      candidates.add(normalized.slice(0, -1));
    } else if (normalized.endsWith("y")) {
      candidates.add(`${normalized.slice(0, -1)}ies`);
      candidates.add(`${normalized}s`);
    } else {
      candidates.add(`${normalized}s`);
    }
    return Array.from(candidates);
  }

  private recommendationSignature(item: ModelingRelationshipRecommendation): string {
    return `${item.sourceTable}.${item.sourceColumn}->${item.targetTable}.${item.targetColumn}`;
  }

  private normalizeRequiredId(value: string, field: string): string {
    const normalized = value.trim();
    if (!normalized) {
      throw new DomainError("VALIDATION_ERROR", `${field} 不能为空。`, 400, {
        field
      });
    }
    return normalized;
  }

  private normalizeOptionalIdempotencyKey(value?: string): string | undefined {
    if (value === undefined) {
      return undefined;
    }
    const normalized = value.trim();
    if (!normalized) {
      return undefined;
    }
    if (normalized.length > MAX_IDEMPOTENCY_KEY_LENGTH) {
      throw new DomainError(
        "VALIDATION_ERROR",
        `x-idempotency-key 长度不能超过 ${MAX_IDEMPOTENCY_KEY_LENGTH}`,
        400,
        {
          field: "x-idempotency-key"
        }
      );
    }
    return normalized;
  }

  private hashCommitPayload(body: UpsertModelingSetupDto): string {
    const selectedTables = Array.from(
      new Set(body.selectedTables.map((item) => normalizeTableName(item)))
    ).sort((left, right) => left.localeCompare(right));
    const explicitSelection = body.selectedRecommendationIds !== undefined;
    const selectedRecommendationIds = Array.from(
      new Set((body.selectedRecommendationIds ?? []).map((item) => item.trim()))
    ).sort((left, right) => left.localeCompare(right));
    return createHash("sha256")
      .update(
        JSON.stringify({
          policyVersion: body.policyVersion,
          selectedTables,
          selectedRecommendationMode: explicitSelection ? "explicit" : "default",
          selectedRecommendationIds: explicitSelection ? selectedRecommendationIds : null
        })
      )
      .digest("hex");
  }

  private buildCommitIdempotencyScope(input: {
    actorId: string;
    workspaceId: string;
    datasourceId: string;
    idempotencyKey: string;
  }): string {
    return [
      input.actorId.trim(),
      input.workspaceId.trim(),
      input.datasourceId.trim(),
      "POST",
      input.idempotencyKey
    ].join("::");
  }

  private readCommitIdempotencyRecord(input: {
    scope: string;
    payloadHash: string;
  }): ModelingSetupCommitResponse | null {
    const record = this.commitIdempotencyStore.get(input.scope);
    if (!record) {
      return null;
    }
    if (record.expiresAt <= Date.now()) {
      this.commitIdempotencyStore.delete(input.scope);
      return null;
    }
    if (record.payloadHash !== input.payloadHash) {
      throw new DomainError(
        "IDEMPOTENCY_REPLAY_CONFLICT",
        "相同 x-idempotency-key 不能提交不同内容。",
        409,
        {
          scope: input.scope
        }
      );
    }
    return {
      ...record.response,
      replayed: true
    };
  }

  private pruneCommitIdempotencyStore(): void {
    const now = Date.now();
    for (const [scope, record] of this.commitIdempotencyStore.entries()) {
      if (record.expiresAt <= now) {
        this.commitIdempotencyStore.delete(scope);
      }
    }
  }

  private buildColumnDiscoverySql(type: DatasourceType, tableName: string): string {
    const escapedTableName = this.escapeSqlLiteral(tableName);
    if (type === "mysql") {
      return `
SELECT
  column_name AS columnName,
  data_type AS dataType,
  is_nullable AS isNullable,
  column_key AS columnKey
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name = '${escapedTableName}'
ORDER BY ordinal_position
      `.trim();
    }
    if (type === "postgresql") {
      return `
SELECT
  c.column_name AS columnName,
  c.data_type AS dataType,
  c.is_nullable AS isNullable,
  tc.constraint_type AS constraintType
FROM information_schema.columns c
LEFT JOIN information_schema.key_column_usage kcu
  ON c.table_schema = kcu.table_schema
  AND c.table_name = kcu.table_name
  AND c.column_name = kcu.column_name
LEFT JOIN information_schema.table_constraints tc
  ON kcu.constraint_name = tc.constraint_name
  AND kcu.table_schema = tc.table_schema
WHERE c.table_schema = 'public'
  AND c.table_name = '${escapedTableName}'
ORDER BY c.ordinal_position
      `.trim();
    }
    return `
SELECT
  name AS columnName,
  type AS dataType,
  "notnull" AS notnull,
  pk AS pk
FROM pragma_table_info('${escapedTableName}')
ORDER BY cid
    `.trim();
  }

  private readString(
    row: Record<string, unknown>,
    candidateKeys: string[]
  ): string | undefined {
    for (const key of candidateKeys) {
      const value = row[key];
      if (typeof value !== "string") {
        continue;
      }
      const normalized = value.trim();
      if (normalized) {
        return normalized;
      }
    }
    return undefined;
  }

  private readBooleanLike(value: unknown): boolean | undefined {
    if (typeof value === "boolean") {
      return value;
    }
    if (typeof value === "number") {
      if (value === 0) {
        return false;
      }
      if (value === 1) {
        return true;
      }
      return undefined;
    }
    if (typeof value !== "string") {
      return undefined;
    }
    const normalized = value.trim().toLowerCase();
    if (!normalized) {
      return undefined;
    }
    if (normalized === "true" || normalized === "yes" || normalized === "y") {
      return true;
    }
    if (normalized === "false" || normalized === "no" || normalized === "n") {
      return false;
    }
    if (normalized === "1") {
      return true;
    }
    if (normalized === "0") {
      return false;
    }
    if (normalized === "not null") {
      return true;
    }
    if (normalized === "null") {
      return false;
    }
    if (normalized === "pri" || normalized === "primary key") {
      return true;
    }
    return undefined;
  }

  private toModelName(tableName: string): string {
    return tableName
      .split(/[_\s-]+/)
      .filter((item) => item.length > 0)
      .map((item) => `${item[0]?.toUpperCase() ?? ""}${item.slice(1)}`)
      .join("");
  }

  private escapeSqlLiteral(value: string): string {
    return value.replace(/'/g, "''");
  }
}
