import { createHash } from "node:crypto";
import { Injectable, Optional } from "@nestjs/common";
import type { Datasource, DatasourceType } from "@text2sql/shared-types";
import { DomainError } from "../../../common/domain-error";
import {
  WorkspaceModelingSchemaChangeDetectorService,
  type ModelingSchemaChangeGroup
} from "./workspace-modeling-schema-change-detector.service";
import type { ModelingGraphPayload } from "../../platform/data/persistence/modeling-graph.types";
import { DatasourceRepository, ModelingGraphRepository } from "../../platform/data/persistence";
import { ModelingSchemaChangeRepository } from "../../platform/data/persistence/modeling-schema-change.repository";
import { QueryExecutorRouterService } from "../../platform/data/query";
import type { DetectModelingSchemaChangeDto } from "./dto/detect-modeling-schema-change.dto";
import type { GetModelingPreviewDto } from "./dto/get-modeling-preview.dto";
import type { UpsertModelingGraphDto } from "./dto/upsert-modeling-graph.dto";
import type { UpsertModelingSetupDto } from "./dto/upsert-modeling-setup.dto";
import type { ResolveModelingSchemaChangeDto } from "./dto/resolve-modeling-schema-change.dto";
import { WorkspaceCalculatedFieldExpressionValidatorService } from "./workspace-calculated-field-expression-validator.service";
import { WorkspaceDatasourceService } from "./workspace-datasource.service";
import { WorkspaceRelationshipService } from "./workspace-relationship.service";

type Actor = {
  id: string;
  role: "admin" | "user";
  workspaceRoles?: Record<string, "admin" | "member">;
  isSystemAdmin?: boolean;
};

type ModelingSetupColumn = {
  name: string;
  dataType: string;
  isNullable: boolean;
  isPrimaryKey: boolean;
};

type ModelingSetupModel = {
  id: string;
  tableName: string;
  modelName: string;
  columns: ModelingSetupColumn[];
};

type ModelingRelationshipRecommendation = {
  id: string;
  name: string;
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
  confidence: number;
  reason: "foreign_key_constraint" | "fk_naming_suffix";
  isAutoGenerated: true;
  bridge: {
    left: {
      dataset: string;
      table: string;
      column: string;
    };
    right: {
      dataset: string;
      table: string;
      column: string;
    };
    operator: "eq";
    confidence: number;
  };
};

type ModelingSetupContext = {
  policyVersion: number;
  selectedTables: string[];
};

type ModelingSetupCommitResponse = {
  stage: "setup_commit_applied";
  workspaceId: string;
  datasourceId: string;
  policyVersion: number;
  selectedTables: string[];
  committedRelationshipIds: string[];
  committedRelationshipCount: number;
  draft: {
    revision: number;
    graphHash: string;
    edgeCount: number;
    updatedAt: string;
  };
  replayed: boolean;
};

type CommitIdempotencyRecord = {
  payloadHash: string;
  response: ModelingSetupCommitResponse;
  expiresAt: number;
};

type ModelingGraphSnapshotResponse = {
  workspaceId: string;
  datasourceId: string;
  activeRevision?: number;
  revisionSummary: {
    draftRevision?: number;
    activeRevision?: number;
    deployState: "undeployed" | "synced";
  };
  draft: {
    policyVersion: number;
    revision: number;
    graphHash: string;
    updatedAt: string;
    updatedByActorId?: string;
    graphPayload: ModelingGraphPayload;
  } | null;
};

type ModelingPreviewResponse = {
  stage: "modeling_preview_ready";
  workspaceId: string;
  datasourceId: string;
  targetKind: "model" | "view";
  targetId: string;
  limit: number;
  rowCount: number;
  truncated: boolean;
  columns: string[];
  rows: Array<Record<string, unknown>>;
};

type ForeignKeyConstraint = {
  sourceTable: string;
  sourceColumn: string;
  targetTable: string;
  targetColumn: string;
};

type ModelingSchemaChangeKind = "deleted_table" | "deleted_column" | "modified_column_type" | "other";

type ModelingSchemaChangeStatus = "detected" | "resolved";

type ModelingSchemaChangeImpact = {
  models: string[];
  relationships: string[];
  calculatedFields: string[];
  views: string[];
};

type ModelingSchemaChangeDetail = {
  id: string;
  kind: ModelingSchemaChangeKind;
  status: ModelingSchemaChangeStatus;
  summary: string;
  tableName: string;
  modelId?: string;
  columnName?: string;
  expectedDataType?: string;
  currentDataType?: string | null;
  impact: ModelingSchemaChangeImpact;
};

type ModelingSchemaChangeState = {
  highRiskStatus: "low" | "high";
  unresolvedHighRiskCount: number;
  unresolvedSchemaChangeIds: string[];
};

type ModelingSchemaChangeDetectResponse = {
  stage: "schema_change_detected";
  workspaceId: string;
  datasourceId: string;
  policyVersion: number;
  highRiskStatus: "low" | "high";
  unresolvedHighRiskCount: number;
  summary: {
    deletedTableCount: number;
    deletedColumnCount: number;
    modifiedColumnCount: number;
    otherCount: number;
    totalCount: number;
  };
  changes: ModelingSchemaChangeGroup;
  draft: {
    revision: number;
    graphHash: string;
    updatedAt: string;
  } | null;
};

type ModelingSchemaChangeResolveResponse = {
  stage: "schema_change_resolved";
  workspaceId: string;
  datasourceId: string;
  policyVersion: number;
  schemaChangeId: string;
  alreadyResolved: boolean;
  highRiskStatus: "low" | "high";
  unresolvedHighRiskCount: number;
  schemaChange: ModelingSchemaChangeDetail;
  draft: {
    revision: number;
    graphHash: string;
    updatedAt: string;
  };
};

const MAX_IDEMPOTENCY_KEY_LENGTH = 128;
const IDEMPOTENCY_TTL_MS = 24 * 60 * 60 * 1000;

const normalizeTableName = (value: string): string => value.trim().toLowerCase();

@Injectable()
export class WorkspaceModelingService {
  private readonly commitIdempotencyStore = new Map<string, CommitIdempotencyRecord>();
  private readonly schemaChangeDetector = new WorkspaceModelingSchemaChangeDetectorService();
  private readonly modelingSchemaChangeRepository = new ModelingSchemaChangeRepository();

  constructor(
    private readonly workspaceDatasourceService: WorkspaceDatasourceService,
    private readonly workspaceRelationshipService: WorkspaceRelationshipService,
    private readonly datasourceRepository: DatasourceRepository,
    private readonly queryExecutorRouter: QueryExecutorRouterService,
    private readonly calculatedFieldExpressionValidator: WorkspaceCalculatedFieldExpressionValidatorService =
      new WorkspaceCalculatedFieldExpressionValidatorService(),
    @Optional() private readonly modelingGraphRepository?: ModelingGraphRepository
  ) {}

  async listSetupTables(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string
  ): Promise<{
    stage: "table_selection_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    items: string[];
    discoveredTableCount: number;
    restrictedTableCount: number;
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");

    const [tableResult, permissionResult] = await Promise.all([
      this.workspaceDatasourceService.listDatasourceTables(actor, workspaceId, datasourceId),
      this.workspaceDatasourceService.listDatasourceTablePermissions(
        actor,
        workspaceId,
        datasourceId
      )
    ]);
    const discoveredSet = new Set(tableResult.items.map((item) => item.toLowerCase()));
    const allowedTables = permissionResult.tableNames
      .filter((tableName) => discoveredSet.has(tableName))
      .sort((left, right) => left.localeCompare(right));

    return {
      stage: "table_selection_ready",
      workspaceId,
      datasourceId,
      policyVersion: permissionResult.policyVersion,
      items: allowedTables,
      discoveredTableCount: tableResult.items.length,
      restrictedTableCount: Math.max(0, tableResult.items.length - allowedTables.length)
    };
  }

  async saveSelectedTables(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_tables_saved";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTableNames: string[];
    impactSummary: {
      beforeCount: number;
      afterCount: number;
      addedCount: number;
      removedCount: number;
      retainedCount: number;
    };
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveSetupContext(
      actor,
      workspaceId,
      datasourceId,
      body
    );

    return {
      stage: "setup_tables_saved",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      selectedTableNames: context.selectedTables,
      impactSummary: {
        beforeCount: context.selectedTables.length,
        afterCount: context.selectedTables.length,
        addedCount: context.selectedTables.length,
        removedCount: 0,
        retainedCount: context.selectedTables.length
      }
    };
  }

  async recommendSetupRelationships(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_relationship_recommendation_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTableNames: string[];
    suggestions: ModelingRelationshipRecommendation[];
    summary: {
      recommendationCount: number;
      modelCount: number;
      columnCount: number;
    };
  }> {
    const preview = await this.previewSetup(actor, workspaceIdRaw, datasourceIdRaw, body);
    return {
      stage: "setup_relationship_recommendation_ready",
      workspaceId: preview.workspaceId,
      datasourceId: preview.datasourceId,
      policyVersion: preview.policyVersion,
      selectedTableNames: preview.selectedTables,
      suggestions: preview.relationshipRecommendations,
      summary: {
        recommendationCount: preview.summary.recommendationCount,
        modelCount: preview.summary.modelCount,
        columnCount: preview.summary.columnCount
      }
    };
  }

  async previewSetup(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto
  ): Promise<{
    stage: "setup_preview_ready";
    workspaceId: string;
    datasourceId: string;
    policyVersion: number;
    selectedTables: string[];
    models: ModelingSetupModel[];
    relationshipRecommendations: ModelingRelationshipRecommendation[];
    defaultSelectedRecommendationIds: string[];
    summary: {
      modelCount: number;
      columnCount: number;
      recommendationCount: number;
    };
  }> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveSetupContext(
      actor,
      workspaceId,
      datasourceId,
      body
    );
    const datasource = await this.loadDatasourceOrThrow(datasourceId);
    const models = await this.introspectModels(datasource, context.selectedTables);
    const constraints = await this.discoverForeignKeyConstraints(
      datasource,
      context.selectedTables
    );
    const recommendations = this.recommendRelationships({
      datasourceId,
      models,
      constraints
    });

    return {
      stage: "setup_preview_ready",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      selectedTables: context.selectedTables,
      models,
      relationshipRecommendations: recommendations,
      defaultSelectedRecommendationIds: recommendations.map((item) => item.id),
      summary: {
        modelCount: models.length,
        columnCount: models.reduce((sum, model) => sum + model.columns.length, 0),
        recommendationCount: recommendations.length
      }
    };
  }

  async commitSetup(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingSetupDto,
    idempotencyKeyRaw?: string
  ): Promise<ModelingSetupCommitResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const idempotencyKey = this.normalizeOptionalIdempotencyKey(idempotencyKeyRaw);
    const payloadHash = this.hashCommitPayload(body);
    const idempotencyScope = idempotencyKey
      ? this.buildCommitIdempotencyScope({
          actorId: actor.id,
          workspaceId,
          datasourceId,
          idempotencyKey
        })
      : undefined;
    if (idempotencyScope) {
      this.pruneCommitIdempotencyStore();
      const replayed = this.readCommitIdempotencyRecord({
        scope: idempotencyScope,
        payloadHash
      });
      if (replayed) {
        return replayed;
      }
    }

    const preview = await this.previewSetup(actor, workspaceId, datasourceId, body);
    const recommendationMap = new Map(
      preview.relationshipRecommendations.map((item) => [item.id, item])
    );
    const selectedRecommendationIds =
      body.selectedRecommendationIds === undefined
        ? preview.defaultSelectedRecommendationIds
        : body.selectedRecommendationIds;

    const missingRecommendationIds = selectedRecommendationIds.filter(
      (item) => !recommendationMap.has(item)
    );
    if (missingRecommendationIds.length > 0) {
      throw new DomainError(
        "WORKSPACE_MODELING_SETUP_RELATIONSHIP_NOT_FOUND",
        "提交的关系建议不存在于当前 setup 预览结果。",
        400,
        {
          missingRecommendationIds
        }
      );
    }

    const committedRecommendations = selectedRecommendationIds
      .map((item) => recommendationMap.get(item)!)
      .sort((left, right) => left.id.localeCompare(right.id));
    const committedEdges = committedRecommendations.map((item) => ({
      id: item.id,
      name: item.name,
      bridge: item.bridge
    }));
    const replaced = await this.workspaceRelationshipService.replaceDraft(
      actor,
      workspaceId,
      datasourceId,
      {
        policyVersion: preview.policyVersion,
        edges: committedEdges,
        modelingGraphPayload: this.buildSetupModelingGraphPayload(
          preview.models,
          committedRecommendations
        )
      }
    );

    const response: ModelingSetupCommitResponse = {
      stage: "setup_commit_applied",
      workspaceId,
      datasourceId,
      policyVersion: preview.policyVersion,
      selectedTables: preview.selectedTables,
      committedRelationshipIds: committedRecommendations.map((item) => item.id),
      committedRelationshipCount: committedRecommendations.length,
      draft: {
        revision: replaced.draft.revision,
        graphHash: replaced.draft.graphHash,
        edgeCount: replaced.draft.edges.length,
        updatedAt: replaced.draft.updatedAt
      },
      replayed: false
    };

    if (idempotencyScope) {
      this.commitIdempotencyStore.set(idempotencyScope, {
        payloadHash,
        response,
        expiresAt: Date.now() + IDEMPOTENCY_TTL_MS
      });
    }

    return response;
  }

  async getModelingGraph(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string
  ): Promise<ModelingGraphSnapshotResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const draftState = await this.workspaceRelationshipService.getDraft(
      actor,
      workspaceId,
      datasourceId
    );
    const draft = draftState.draft;
    if (!draft) {
      const revisionSummary = this.buildRevisionSummary(undefined, draftState.activeRevision);
      return {
        workspaceId,
        datasourceId,
        activeRevision: draftState.activeRevision,
        revisionSummary,
        draft: null
      };
    }
    const graphPayload = await this.resolveGraphPayloadFromDraft({
      workspaceId,
      datasourceId,
      revision: draft.revision,
      edges: draft.edges
    });
    const revisionSummary = this.buildRevisionSummary(
      draft.revision,
      draftState.activeRevision
    );
    return {
      workspaceId,
      datasourceId,
      activeRevision: draftState.activeRevision,
      revisionSummary,
      draft: {
        policyVersion: draft.policyVersion,
        revision: draft.revision,
        graphHash: draft.graphHash,
        updatedAt: draft.updatedAt,
        updatedByActorId: draft.updatedByActorId,
        graphPayload
      }
    };
  }

  async upsertModelingGraph(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: UpsertModelingGraphDto
  ): Promise<ModelingGraphSnapshotResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const current = await this.getModelingGraph(actor, workspaceId, datasourceId);
    const permissionResult = await this.workspaceDatasourceService.listDatasourceTablePermissions(
      actor,
      workspaceId,
      datasourceId
    );
    if (permissionResult.policyVersion !== body.policyVersion) {
      throw new DomainError(
        "WORKSPACE_DATASOURCE_POLICY_VERSION_CONFLICT",
        "policyVersion 已过期，请刷新后重试。",
        409,
        {
          workspaceId,
          datasourceId,
          expectedPolicyVersion: permissionResult.policyVersion,
          providedPolicyVersion: body.policyVersion
        }
      );
    }
    const basePayload = current.draft?.graphPayload ?? this.emptyModelingGraphPayload();
    const patch = this.buildModelingGraphPatch(body, datasourceId);
    const mergedPayload = this.mergeModelingGraphPayload(basePayload, patch);
    this.assertModelsAllowed(mergedPayload, permissionResult.tableNames, workspaceId, datasourceId);
    this.calculatedFieldExpressionValidator.validate(mergedPayload);
    const edges = this.extractEdgesFromModelingPayload(mergedPayload);
    const replaced = await this.workspaceRelationshipService.replaceDraft(
      actor,
      workspaceId,
      datasourceId,
      {
        policyVersion: permissionResult.policyVersion,
        edges,
        modelingGraphPayload: mergedPayload
      }
    );
    return {
      workspaceId,
      datasourceId,
      activeRevision: current.activeRevision,
      revisionSummary: this.buildRevisionSummary(
        replaced.draft.revision,
        current.activeRevision
      ),
      draft: {
        policyVersion: replaced.draft.policyVersion,
        revision: replaced.draft.revision,
        graphHash: replaced.draft.graphHash,
        updatedAt: replaced.draft.updatedAt,
        updatedByActorId: replaced.draft.updatedByActorId,
        graphPayload: mergedPayload
      }
    };
  }

  async getModelingPreview(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: GetModelingPreviewDto
  ): Promise<ModelingPreviewResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const targetId = this.normalizeRequiredId(body.targetId, "targetId");
    const limit = Math.min(100, Math.max(1, body.limit ?? 100));
    const targetKind = body.targetKind;
    const snapshot = await this.getModelingGraph(actor, workspaceId, datasourceId);
    const payload = snapshot.draft?.graphPayload;
    if (!payload) {
      throw new DomainError(
        "WORKSPACE_MODELING_PREVIEW_TARGET_NOT_FOUND",
        "当前无可预览的 modeling draft。",
        404,
        {
          workspaceId,
          datasourceId,
          targetKind,
          targetId
        }
      );
    }

    const datasource = await this.loadDatasourceOrThrow(datasourceId);
    let sql = "";
    if (targetKind === "model") {
      const model = payload.models.find((item) => item.id === targetId);
      if (!model) {
        throw new DomainError(
          "WORKSPACE_MODELING_PREVIEW_TARGET_NOT_FOUND",
          "未找到目标 model。",
          404,
          {
            workspaceId,
            datasourceId,
            targetKind,
            targetId
          }
        );
      }
      sql = this.buildModelPreviewSql(datasource.type, model.tableName);
    } else {
      const view = payload.views.find((item) => item.id === targetId);
      if (!view) {
        throw new DomainError(
          "WORKSPACE_MODELING_PREVIEW_TARGET_NOT_FOUND",
          "未找到目标 view。",
          404,
          {
            workspaceId,
            datasourceId,
            targetKind,
            targetId
          }
        );
      }
      sql = this.buildViewPreviewSql(view.sql);
    }

    try {
      const queryResult = await this.queryExecutorRouter.execute({
        datasource,
        sql,
        limit: limit + 1
      });
      const rows = queryResult.rows
        .slice(0, limit)
        .map((item) => (item && typeof item === "object" ? (item as Record<string, unknown>) : {}));
      const columns = Array.from(
        rows.reduce((set, row) => {
          Object.keys(row).forEach((column) => {
            set.add(column);
          });
          return set;
        }, new Set<string>())
      ).sort((left, right) => left.localeCompare(right));
      return {
        stage: "modeling_preview_ready",
        workspaceId,
        datasourceId,
        targetKind,
        targetId,
        limit,
        rowCount: rows.length,
        truncated: queryResult.rows.length > limit,
        columns,
        rows
      };
    } catch (error) {
      throw new DomainError(
        "WORKSPACE_MODELING_PREVIEW_QUERY_FAILED",
        "modeling preview 查询失败。",
        400,
        {
          workspaceId,
          datasourceId,
          targetKind,
          targetId,
          cause: error instanceof Error ? error.message : String(error)
        }
      );
    }
  }

  async describeModelingSchemaChangeState(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string
  ): Promise<ModelingSchemaChangeState> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const snapshot = await this.getModelingGraph(actor, workspaceId, datasourceId);
    return this.modelingSchemaChangeRepository.buildState(
      snapshot.draft?.graphPayload.schemaChanges ?? []
    );
  }

  async detectModelingSchemaChanges(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: DetectModelingSchemaChangeDto
  ): Promise<ModelingSchemaChangeDetectResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveModelingSchemaChangeContext(
      actor,
      workspaceId,
      datasourceId,
      body.policyVersion
    );
    const currentGraph = await this.getModelingGraph(actor, workspaceId, datasourceId);
    const currentPayload = currentGraph.draft?.graphPayload ?? this.emptyModelingGraphPayload();
    const detected = await this.schemaChangeDetector.detect({
      currentPayload,
      liveTableNames: context.liveTableNames,
      loadLiveColumns: async (tableName: string) =>
        this.loadTableColumns(context.datasource, tableName)
    });
    const mergedSchemaChanges = this.modelingSchemaChangeRepository.mergeDetected(
      currentPayload.schemaChanges,
      detected.items
    );
    const filteredSchemaChanges = body.includeResolved
      ? mergedSchemaChanges
      : mergedSchemaChanges.filter((item) => item.status === "detected");
    const shouldPersist = currentGraph.draft
      ? !this.modelingSchemaChangeRepository.areEqual(
          currentPayload.schemaChanges,
          mergedSchemaChanges
        )
      : mergedSchemaChanges.length > 0;
    let draft = currentGraph.draft
      ? {
          revision: currentGraph.draft.revision,
          graphHash: currentGraph.draft.graphHash,
          updatedAt: currentGraph.draft.updatedAt
        }
      : null;

    if (shouldPersist) {
      const replaced = await this.workspaceRelationshipService.replaceDraft(
        actor,
        workspaceId,
        datasourceId,
        {
          policyVersion: context.policyVersion,
          edges: this.extractEdgesFromModelingPayload({
            ...currentPayload,
            schemaChanges: mergedSchemaChanges
          }),
          modelingGraphPayload: {
            ...currentPayload,
            schemaChanges: mergedSchemaChanges
          }
        }
      );
      draft = {
        revision: replaced.draft.revision,
        graphHash: replaced.draft.graphHash,
        updatedAt: replaced.draft.updatedAt
      };
    }

    const state = this.modelingSchemaChangeRepository.buildState(filteredSchemaChanges);
    this.modelingSchemaChangeRepository.saveScopeRecords({
      workspaceId,
      datasourceId,
      records: mergedSchemaChanges
    });
    this.modelingSchemaChangeRepository.appendAuditEvent({
      workspaceId,
      datasourceId,
      event: {
        action: "detect",
        outcome: "detected",
        policyVersion: context.policyVersion,
        detectedCount: detected.items.length,
        mergedCount: mergedSchemaChanges.length,
        unresolvedHighRiskCount: state.unresolvedHighRiskCount,
        persisted: shouldPersist
      }
    });
    return {
      stage: "schema_change_detected",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      highRiskStatus: state.highRiskStatus,
      unresolvedHighRiskCount: state.unresolvedHighRiskCount,
      summary: {
        deletedTableCount: detected.grouped.deletedTables.length,
        deletedColumnCount: detected.grouped.deletedColumns.length,
        modifiedColumnCount: detected.grouped.modifiedColumns.length,
        otherCount: detected.grouped.other.length,
        totalCount: detected.grouped.deleted.length + detected.grouped.modified.length + detected.grouped.other.length
      },
      changes: {
        ...detected.grouped,
        deleted: detected.grouped.deleted.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        ),
        modified: detected.grouped.modified.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        ),
        deletedTables: detected.grouped.deletedTables.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        ),
        deletedColumns: detected.grouped.deletedColumns.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        ),
        modifiedColumns: detected.grouped.modifiedColumns.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        ),
        other: detected.grouped.other.filter((item) =>
          body.includeResolved ? true : item.status === "detected"
        )
      },
      draft
    };
  }

  async resolveModelingSchemaChange(
    actor: Actor,
    workspaceIdRaw: string,
    datasourceIdRaw: string,
    body: ResolveModelingSchemaChangeDto
  ): Promise<ModelingSchemaChangeResolveResponse> {
    const workspaceId = this.normalizeRequiredId(workspaceIdRaw, "workspaceId");
    const datasourceId = this.normalizeRequiredId(datasourceIdRaw, "datasourceId");
    const context = await this.resolveModelingSchemaChangeContext(
      actor,
      workspaceId,
      datasourceId,
      body.policyVersion
    );
    const currentGraph = await this.getModelingGraph(actor, workspaceId, datasourceId);
    const currentPayload = currentGraph.draft?.graphPayload ?? this.emptyModelingGraphPayload();
    const changeId = this.resolveSchemaChangeId(body);
    const currentRecords = await this.schemaChangeDetector.detect({
      currentPayload,
      liveTableNames: context.liveTableNames,
      loadLiveColumns: async (tableName: string) =>
        this.loadTableColumns(context.datasource, tableName)
    });
    const mergedSchemaChanges = this.modelingSchemaChangeRepository.mergeDetected(
      currentPayload.schemaChanges,
      currentRecords.items
    );
    const target = currentRecords.items.find((item) => item.id === changeId);
    const storedTarget = mergedSchemaChanges.find((item) => item.id === changeId);
    if (!target && !storedTarget) {
      this.modelingSchemaChangeRepository.appendAuditEvent({
        workspaceId,
        datasourceId,
        event: {
          action: "resolve",
          outcome: "not_found",
          changeId,
          policyVersion: context.policyVersion
        }
      });
      throw new DomainError(
        "WORKSPACE_MODELING_SCHEMA_CHANGE_NOT_FOUND",
        "未找到 modeling schema change。",
        404,
        {
          workspaceId,
          datasourceId,
          schemaChangeId: changeId
        }
      );
    }

    const resolvedItem =
      target ??
      this.schemaChangeDetector.buildSchemaChangeDetailFromStoredRecord({
        record: storedTarget!,
        currentPayload
      }) ??
      this.buildSchemaChangeDetailFromStoredRecord({
        record: storedTarget!,
        currentPayload
      });
    if (!resolvedItem) {
      throw new DomainError(
        "WORKSPACE_MODELING_SCHEMA_CHANGE_NOT_FOUND",
        "未找到 modeling schema change。",
        404,
        {
          workspaceId,
          datasourceId,
          schemaChangeId: changeId
        }
      );
    }

    const resolveResult = this.modelingSchemaChangeRepository.resolveByChangeId(
      mergedSchemaChanges,
      changeId
    );
    if (!resolveResult.found) {
      throw new DomainError(
        "WORKSPACE_MODELING_SCHEMA_CHANGE_NOT_FOUND",
        "未找到 modeling schema change。",
        404,
        {
          workspaceId,
          datasourceId,
          schemaChangeId: changeId
        }
      );
    }

    if (resolvedItem.kind === "modified_column_type" && !resolveResult.alreadyResolved) {
      throw new DomainError(
        "WORKSPACE_MODELING_SCHEMA_CHANGE_MANUAL_RESOLUTION_REQUIRED",
        "列类型变化需先人工重建建模对象后重新 Detect，暂不支持直接 Resolve。",
        409,
        {
          workspaceId,
          datasourceId,
          schemaChangeId: changeId,
          kind: resolvedItem.kind
        }
      );
    }

    if (resolveResult.alreadyResolved) {
      const draftSnapshot = currentGraph.draft;
      if (!draftSnapshot) {
        throw new DomainError(
          "WORKSPACE_MODELING_SCHEMA_CHANGE_NOT_FOUND",
          "未找到 modeling schema change。",
          404,
          {
            workspaceId,
            datasourceId,
            schemaChangeId: changeId
          }
        );
      }
      const state = this.modelingSchemaChangeRepository.buildState(mergedSchemaChanges);
      this.modelingSchemaChangeRepository.saveScopeRecords({
        workspaceId,
        datasourceId,
        records: mergedSchemaChanges
      });
      this.modelingSchemaChangeRepository.appendAuditEvent({
        workspaceId,
        datasourceId,
        event: {
          action: "resolve",
          outcome: "already_resolved",
          changeId,
          policyVersion: context.policyVersion,
          unresolvedHighRiskCount: state.unresolvedHighRiskCount
        }
      });
      return {
        stage: "schema_change_resolved",
        workspaceId,
        datasourceId,
        policyVersion: context.policyVersion,
        schemaChangeId: changeId,
        alreadyResolved: true,
        highRiskStatus: state.highRiskStatus,
        unresolvedHighRiskCount: state.unresolvedHighRiskCount,
        schemaChange: resolvedItem,
        draft: {
          revision: draftSnapshot.revision,
          graphHash: draftSnapshot.graphHash,
          updatedAt: draftSnapshot.updatedAt
        }
      };
    }

    let nextPayload: ModelingGraphPayload = currentPayload;
    let updatedSchemaChanges = resolveResult.updatedRecords;

    if (this.isAutoResolvableSchemaChangeKind(resolvedItem.kind)) {
      nextPayload = this.applyAutoResolutionForSchemaChange({
        currentPayload,
        schemaChange: resolvedItem
      });
      const postResolutionDetected = await this.schemaChangeDetector.detect({
        currentPayload: nextPayload,
        liveTableNames: context.liveTableNames,
        loadLiveColumns: async (tableName: string) =>
          this.loadTableColumns(context.datasource, tableName)
      });
      updatedSchemaChanges = this.modelingSchemaChangeRepository.mergeDetected(
        updatedSchemaChanges,
        postResolutionDetected.items
      );
    }

    const replaced = await this.workspaceRelationshipService.replaceDraft(
      actor,
      workspaceId,
      datasourceId,
      {
        policyVersion: context.policyVersion,
        edges: this.extractEdgesFromModelingPayload({
          ...nextPayload,
          schemaChanges: updatedSchemaChanges
        }),
        modelingGraphPayload: {
          ...nextPayload,
          schemaChanges: updatedSchemaChanges
        }
      }
    );
    this.modelingSchemaChangeRepository.saveScopeRecords({
      workspaceId,
      datasourceId,
      records: updatedSchemaChanges
    });
    const state = this.modelingSchemaChangeRepository.buildState(updatedSchemaChanges);
    this.modelingSchemaChangeRepository.appendAuditEvent({
      workspaceId,
      datasourceId,
      event: {
        action: "resolve",
        outcome: "resolved",
        changeId,
        policyVersion: context.policyVersion,
        unresolvedHighRiskCount: state.unresolvedHighRiskCount
      }
    });
    return {
      stage: "schema_change_resolved",
      workspaceId,
      datasourceId,
      policyVersion: context.policyVersion,
      schemaChangeId: changeId,
      alreadyResolved: false,
      highRiskStatus: state.highRiskStatus,
      unresolvedHighRiskCount: state.unresolvedHighRiskCount,
      schemaChange: {
        ...resolvedItem,
        status: "resolved"
      },
      draft: {
        revision: replaced.draft.revision,
        graphHash: replaced.draft.graphHash,
        updatedAt: replaced.draft.updatedAt
      }
    };
  }

  private isAutoResolvableSchemaChangeKind(
    kind: ModelingSchemaChangeKind
  ): kind is "deleted_table" | "deleted_column" {
    return kind === "deleted_table" || kind === "deleted_column";
  }

  private applyAutoResolutionForSchemaChange(input: {
    currentPayload: ModelingGraphPayload;
    schemaChange: ModelingSchemaChangeDetail;
  }): ModelingGraphPayload {
    const tableName = normalizeTableName(input.schemaChange.tableName);
    const columnName = input.schemaChange.columnName
      ? normalizeTableName(input.schemaChange.columnName)
      : undefined;
    const schemaChangeModelIds = new Set(input.schemaChange.impact.models);
    const schemaChangeRelationshipIds = new Set(input.schemaChange.impact.relationships);
    const schemaChangeCalculatedFieldIds = new Set(input.schemaChange.impact.calculatedFields);
    const schemaChangeViewIds = new Set(input.schemaChange.impact.views);

    for (const model of input.currentPayload.models) {
      const isSameTable = normalizeTableName(model.tableName) === tableName;
      const isSameModelId =
        input.schemaChange.modelId !== undefined && model.id === input.schemaChange.modelId;
      if (isSameTable || isSameModelId) {
        schemaChangeModelIds.add(model.id);
      }
    }

    const models =
      input.schemaChange.kind === "deleted_table"
        ? input.currentPayload.models.filter((model) => {
            const isSameTable = normalizeTableName(model.tableName) === tableName;
            return !(isSameTable || schemaChangeModelIds.has(model.id));
          })
        : input.currentPayload.models.map((model) => {
            if (!schemaChangeModelIds.has(model.id) || !columnName) {
              return model;
            }
            return {
              ...model,
              columns: model.columns.filter(
                (column) => normalizeTableName(column.name) !== columnName
              )
            };
          });

    const relationships = input.currentPayload.relationships.filter((relationship) => {
      if (schemaChangeRelationshipIds.has(relationship.id)) {
        return false;
      }
      const leftTable = normalizeTableName(relationship.bridge.left.table);
      const rightTable = normalizeTableName(relationship.bridge.right.table);
      if (input.schemaChange.kind === "deleted_table") {
        return leftTable !== tableName && rightTable !== tableName;
      }
      if (!columnName) {
        return true;
      }
      const leftColumn = normalizeTableName(relationship.bridge.left.column);
      const rightColumn = normalizeTableName(relationship.bridge.right.column);
      const leftMatches = leftTable === tableName && leftColumn === columnName;
      const rightMatches = rightTable === tableName && rightColumn === columnName;
      return !leftMatches && !rightMatches;
    });

    const calculatedFields = input.currentPayload.calculatedFields.filter((field) => {
      if (schemaChangeCalculatedFieldIds.has(field.id)) {
        return false;
      }
      if (input.schemaChange.kind === "deleted_table") {
        return !schemaChangeModelIds.has(field.modelId);
      }
      return true;
    });

    const views = input.currentPayload.views.filter((view) => !schemaChangeViewIds.has(view.id));

    return {
      ...input.currentPayload,
      models: [...models].sort((left, right) => left.id.localeCompare(right.id)),
      relationships: [...relationships].sort((left, right) => left.id.localeCompare(right.id)),
      calculatedFields: [...calculatedFields].sort((left, right) => left.id.localeCompare(right.id)),
      views: [...views].sort((left, right) => left.id.localeCompare(right.id))
    };
  }

  private emptyModelingGraphPayload(): ModelingGraphPayload {
    return {
      models: [],
      relationships: [],
      calculatedFields: [],
      views: [],
      schemaChanges: []
    };
  }

  private buildModelingSchemaChangeState(
    schemaChanges: Array<{
      id: string;
      status: ModelingSchemaChangeStatus;
    }>
  ): ModelingSchemaChangeState {
    return this.modelingSchemaChangeRepository.buildState(schemaChanges);
  }

  private resolveSchemaChangeId(body: ResolveModelingSchemaChangeDto): string {
    const rawId = body.changeId ?? body.schemaChangeId;
    const normalized = rawId?.trim();
    if (!normalized) {
      throw new DomainError("VALIDATION_ERROR", "changeId 不能为空。", 400, {
        field: "changeId"
      });
    }
    return normalized;
  }

  private async resolveModelingSchemaChangeContext(
    actor: Actor,
    workspaceId: string,
    datasourceId: string,
    policyVersion?: number
  ): Promise<{
    policyVersion: number;
    datasource: Datasource;
    liveTableNames: string[];
  }> {
    const [permissionResult, datasource, tableResult] = await Promise.all([
      this.workspaceDatasourceService.listDatasourceTablePermissions(
        actor,
        workspaceId,
        datasourceId
      ),
      this.loadDatasourceOrThrow(datasourceId),
      this.workspaceDatasourceService.listDatasourceTables(actor, workspaceId, datasourceId)
    ]);

    if (
      policyVersion !== undefined &&
      permissionResult.policyVersion !== policyVersion
    ) {
      throw new DomainError(
        "WORKSPACE_DATASOURCE_POLICY_VERSION_CONFLICT",
        "policyVersion 已过期，请刷新后重试。",
        409,
        {
          workspaceId,
          datasourceId,
          expectedPolicyVersion: permissionResult.policyVersion,
          providedPolicyVersion: policyVersion
        }
      );
    }

    return {
      policyVersion: permissionResult.policyVersion,
      datasource,
      liveTableNames: tableResult.items.map((item) => normalizeTableName(item))
    };
  }

  private async collectModelingSchemaChangeDetection(input: {
    workspaceId: string;
    datasourceId: string;
    datasource: Datasource;
    liveTableNames: string[];
    currentPayload: ModelingGraphPayload;
  }): Promise<{
    items: ModelingSchemaChangeDetail[];
    grouped: ModelingSchemaChangeGroup;
  }> {
    const liveTableSet = new Set(
      input.liveTableNames.map((item) => normalizeTableName(item))
    );
    const currentSchemaChangeById = new Map(
      input.currentPayload.schemaChanges.map((item) => [item.id, item])
    );
    const items: ModelingSchemaChangeDetail[] = [];

    for (const model of [...input.currentPayload.models].sort((left, right) =>
      left.id.localeCompare(right.id)
    )) {
      const tableName = normalizeTableName(model.tableName);
      const modelId = model.id;
      const existingTableRecord = currentSchemaChangeById.get(
        this.buildSchemaChangeId("deleted_table", tableName)
      );

      if (!liveTableSet.has(tableName)) {
        items.push(
          this.buildModelingSchemaChangeDetail({
            kind: "deleted_table",
            tableName,
            modelId,
            currentPayload: input.currentPayload,
            existingRecord: existingTableRecord
          })
        );
        continue;
      }

      const liveColumns = await this.loadTableColumns(input.datasource, tableName);
      const liveColumnByName = new Map(
        liveColumns.map((item) => [normalizeTableName(item.name), item])
      );

      for (const column of [...model.columns].sort((left, right) =>
        left.name.localeCompare(right.name)
      )) {
        const columnName = normalizeTableName(column.name);
        const liveColumn = liveColumnByName.get(columnName);
        if (!liveColumn) {
          items.push(
            this.buildModelingSchemaChangeDetail({
              kind: "deleted_column",
              tableName,
              modelId,
              columnName,
              expectedDataType: column.dataType,
              currentDataType: null,
              currentPayload: input.currentPayload,
              existingRecord: currentSchemaChangeById.get(
                this.buildSchemaChangeId("deleted_column", tableName, columnName)
              )
            })
          );
          continue;
        }

        const expectedDataType = column.dataType.toLowerCase();
        const currentDataType = liveColumn.dataType.toLowerCase();
        const columnChanged =
          expectedDataType !== currentDataType ||
          column.isNullable !== liveColumn.isNullable ||
          column.isPrimaryKey !== liveColumn.isPrimaryKey;

        if (columnChanged) {
          items.push(
            this.buildModelingSchemaChangeDetail({
              kind: "modified_column_type",
              tableName,
              modelId,
              columnName,
              expectedDataType,
              currentDataType,
              currentPayload: input.currentPayload,
              existingRecord: currentSchemaChangeById.get(
                this.buildSchemaChangeId("modified_column_type", tableName, columnName)
              )
            })
          );
        }
      }
    }

    const grouped: ModelingSchemaChangeGroup = {
      deletedTables: items.filter((item) => item.kind === "deleted_table"),
      deletedColumns: items.filter((item) => item.kind === "deleted_column"),
      modifiedColumns: items.filter((item) => item.kind === "modified_column_type"),
      other: items.filter((item) => item.kind === "other"),
      deleted: items.filter(
        (item) => item.kind === "deleted_table" || item.kind === "deleted_column"
      ),
      modified: items.filter((item) => item.kind === "modified_column_type")
    };

    return {
      items,
      grouped
    };
  }

  private buildModelingSchemaChangeDetail(input: {
    kind: ModelingSchemaChangeKind;
    tableName: string;
    modelId: string;
    currentPayload: ModelingGraphPayload;
    existingRecord?: ModelingGraphPayload["schemaChanges"][number];
    columnName?: string;
    expectedDataType?: string;
    currentDataType?: string | null;
  }): ModelingSchemaChangeDetail {
    const id = this.buildSchemaChangeId(
      input.kind,
      input.tableName,
      input.columnName
    );
    const status: ModelingSchemaChangeStatus =
      input.existingRecord?.status === "resolved" ? "resolved" : "detected";
    const impact = this.buildModelingSchemaChangeImpact({
      currentPayload: input.currentPayload,
      tableName: input.tableName,
      modelId: input.modelId,
      columnName: input.columnName
    });
    const tableLabel = input.tableName;
    const columnLabel = input.columnName ? `.${input.columnName}` : "";
    const summary =
      input.kind === "deleted_table"
        ? `数据表 ${tableLabel} 已删除。`
        : input.kind === "deleted_column"
          ? `数据表 ${tableLabel} 的字段 ${input.columnName ?? ""} 已删除。`
          : input.kind === "modified_column_type"
            ? `数据表 ${tableLabel} 的字段 ${input.columnName ?? ""} 类型或约束已变化。`
            : `数据表 ${tableLabel}${columnLabel} 出现其他 schema change。`;

    return {
      id,
      kind: input.kind,
      status,
      summary,
      tableName: tableLabel,
      modelId: input.modelId,
      columnName: input.columnName,
      expectedDataType: input.expectedDataType,
      currentDataType: input.currentDataType,
      impact
    };
  }

  private buildSchemaChangeDetailFromStoredRecord(input: {
    record: ModelingGraphPayload["schemaChanges"][number];
    currentPayload: ModelingGraphPayload;
  }): ModelingSchemaChangeDetail | null {
    const parsed = this.parseSchemaChangeId(input.record.id);
    if (!parsed?.tableName) {
      return null;
    }
    const tableName = parsed.tableName;
    const model = input.currentPayload.models.find(
      (item) => normalizeTableName(item.tableName) === tableName
    );
    const modelId = model?.id ?? parsed.tableName;
    return {
      id: input.record.id,
      kind: parsed.kind ?? input.record.kind,
      status: input.record.status,
      summary: input.record.summary,
      tableName,
      modelId,
      columnName: parsed.columnName,
      impact: this.buildModelingSchemaChangeImpact({
        currentPayload: input.currentPayload,
        tableName,
        modelId,
        columnName: parsed.columnName
      })
    };
  }

  private buildModelingSchemaChangeImpact(input: {
    currentPayload: ModelingGraphPayload;
    tableName: string;
    modelId: string;
    columnName?: string;
  }): ModelingSchemaChangeImpact {
    const tableName = normalizeTableName(input.tableName);
    const columnName = input.columnName ? normalizeTableName(input.columnName) : undefined;
    const models = new Set<string>();
    const relationships = new Set<string>();
    const calculatedFields = new Set<string>();
    const views = new Set<string>();

    for (const model of input.currentPayload.models) {
      if (normalizeTableName(model.tableName) === tableName || model.id === input.modelId) {
        models.add(model.id);
      }
    }

    for (const relationship of input.currentPayload.relationships) {
      const leftMatches =
        normalizeTableName(relationship.bridge.left.table) === tableName &&
        (!columnName || normalizeTableName(relationship.bridge.left.column) === columnName);
      const rightMatches =
        normalizeTableName(relationship.bridge.right.table) === tableName &&
        (!columnName || normalizeTableName(relationship.bridge.right.column) === columnName);
      if (leftMatches || rightMatches) {
        relationships.add(relationship.id);
      }
    }

    for (const field of input.currentPayload.calculatedFields) {
      if (field.modelId === input.modelId) {
        calculatedFields.add(field.id);
      }
    }

    for (const view of input.currentPayload.views) {
      const haystack = [view.name, view.displayName, view.description, view.sql]
        .filter((value): value is string => typeof value === "string")
        .join(" ")
        .toLowerCase();
      if (haystack.includes(tableName) || (columnName ? haystack.includes(columnName) : false)) {
        views.add(view.id);
      }
    }

    return {
      models: Array.from(models).sort((left, right) => left.localeCompare(right)),
      relationships: Array.from(relationships).sort((left, right) => left.localeCompare(right)),
      calculatedFields: Array.from(calculatedFields).sort((left, right) =>
        left.localeCompare(right)
      ),
      views: Array.from(views).sort((left, right) => left.localeCompare(right))
    };
  }

  private mergeModelingSchemaChanges(
    existing: ModelingGraphPayload["schemaChanges"],
    detected: ModelingSchemaChangeDetail[]
  ): ModelingGraphPayload["schemaChanges"] {
    const merged = new Map<string, ModelingGraphPayload["schemaChanges"][number]>();
    for (const item of existing) {
      if (item.status === "resolved") {
        merged.set(item.id, {
          id: item.id,
          status: item.status,
          kind: item.kind,
          summary: item.summary
        });
      }
    }
    for (const item of detected) {
      merged.set(item.id, {
        id: item.id,
        status: item.status,
        kind: item.kind === "other" ? "other" : item.kind,
        summary: item.summary
      });
    }
    return Array.from(merged.values()).sort((left, right) => left.id.localeCompare(right.id));
  }

  private areSchemaChangeRecordsEqual(
    left: ModelingGraphPayload["schemaChanges"],
    right: ModelingGraphPayload["schemaChanges"]
  ): boolean {
    if (left.length !== right.length) {
      return false;
    }
    const normalizedLeft = [...left].sort((a, b) => a.id.localeCompare(b.id));
    const normalizedRight = [...right].sort((a, b) => a.id.localeCompare(b.id));
    return normalizedLeft.every((item, index) => {
      const other = normalizedRight[index];
      return (
        other !== undefined &&
        item.id === other.id &&
        item.status === other.status &&
        item.kind === other.kind &&
        item.summary === other.summary
      );
    });
  }

  private buildSchemaChangeId(
    kind: ModelingSchemaChangeKind,
    tableName: string,
    columnName?: string
  ): string {
    const normalizedTableName = normalizeTableName(tableName);
    const normalizedColumnName = columnName ? normalizeTableName(columnName) : undefined;
    return normalizedColumnName
      ? `schema-change:${kind}:${normalizedTableName}:${normalizedColumnName}`
      : `schema-change:${kind}:${normalizedTableName}`;
  }

  private parseSchemaChangeId(id: string): {
    kind?: ModelingSchemaChangeKind;
    tableName?: string;
    columnName?: string;
  } | null {
    const parts = id.split(":");
    if (parts.length < 3 || parts[0] !== "schema-change") {
      return null;
    }
    const kindRaw = parts[1] as ModelingSchemaChangeKind | undefined;
    const kind =
      kindRaw === "deleted_table" ||
      kindRaw === "deleted_column" ||
      kindRaw === "modified_column_type" ||
      kindRaw === "other"
        ? kindRaw
        : undefined;
    const tableName = parts[2]?.trim().toLowerCase();
    const columnName = parts[3]?.trim().toLowerCase();
    if (!tableName) {
      return null;
    }
    return {
      kind,
      tableName,
      columnName
    };
  }

  private async loadTableColumns(
    datasource: Datasource,
    tableName: string
  ): Promise<
    Array<{
      name: string;
      dataType: string;
      isNullable: boolean;
      isPrimaryKey: boolean;
    }>
  > {
    const queryResult = await this.queryExecutorRouter.execute({
      datasource,
      sql: this.buildColumnDiscoverySql(datasource.type, tableName),
      limit: 200
    });
    return queryResult.rows
      .map((row) => this.readColumnDefinition(row))
      .filter(
        (
          item
        ): item is {
          name: string;
          dataType: string;
          isNullable: boolean;
          isPrimaryKey: boolean;
        } => Boolean(item)
      )
      .sort((left, right) => left.name.localeCompare(right.name));
  }

  private async resolveGraphPayloadFromDraft(input: {
    workspaceId: string;
    datasourceId: string;
    revision: number;
    edges: Array<{
      id: string;
      name?: string;
      bridge: {
        left: {
          dataset: string;
          table: string;
          column: string;
        };
        right: {
          dataset: string;
          table: string;
          column: string;
        };
        operator: "eq";
        confidence: number;
      };
    }>;
  }): Promise<ModelingGraphPayload> {
    if (!this.modelingGraphRepository) {
      return this.buildPayloadFromEdges(input.edges);
    }
    const matched = await this.modelingGraphRepository.findRevision({
      workspaceId: input.workspaceId,
      datasourceId: input.datasourceId,
      revision: input.revision
    });
    if (!matched) {
      return this.buildPayloadFromEdges(input.edges);
    }
    return matched.graphPayload;
  }

  private buildPayloadFromEdges(
    edges: Array<{
      id: string;
      name?: string;
      bridge: {
        left: {
          dataset: string;
          table: string;
          column: string;
        };
        right: {
          dataset: string;
          table: string;
          column: string;
        };
        operator: "eq";
        confidence: number;
      };
    }>
  ): ModelingGraphPayload {
    return {
      models: [],
      relationships: edges
        .map((edge) => ({
          id: edge.id,
          name: edge.name,
          source: "manual" as const,
          confidence: Number(edge.bridge.confidence.toFixed(4)),
          bridge: {
            left: {
              dataset: edge.bridge.left.dataset,
              table: edge.bridge.left.table,
              column: edge.bridge.left.column
            },
            right: {
              dataset: edge.bridge.right.dataset,
              table: edge.bridge.right.table,
              column: edge.bridge.right.column
            },
            operator: "eq" as const,
            confidence: Number(edge.bridge.confidence.toFixed(4))
          }
        }))
        .sort((left, right) => left.id.localeCompare(right.id)),
      calculatedFields: [],
      views: [],
      schemaChanges: []
    };
  }

  private buildModelingGraphPatch(
    body: UpsertModelingGraphDto,
    datasourceId: string
  ): Partial<ModelingGraphPayload> {
    const patch: Partial<ModelingGraphPayload> = {};
    if (body.models) {
      patch.models = body.models.map((item) => this.normalizeModel(item));
    }
    if (body.relationships) {
      patch.relationships = body.relationships.map((item) =>
        this.normalizeRelationship(item, datasourceId)
      );
    }
    if (body.calculatedFields) {
      patch.calculatedFields = body.calculatedFields.map((item) =>
        this.normalizeCalculatedField(item)
      );
    }
    if (body.views) {
      patch.views = body.views.map((item) => this.normalizeView(item));
    }
    if (body.schemaChanges) {
      patch.schemaChanges = body.schemaChanges.map((item) => this.normalizeSchemaChange(item));
    }
    return patch;
  }

  private mergeModelingGraphPayload(
    base: ModelingGraphPayload,
    patch: Partial<ModelingGraphPayload>
  ): ModelingGraphPayload {
    return {
      models: (patch.models ?? base.models).sort((left, right) => left.id.localeCompare(right.id)),
      relationships: (patch.relationships ?? base.relationships).sort((left, right) =>
        left.id.localeCompare(right.id)
      ),
      calculatedFields: (patch.calculatedFields ?? base.calculatedFields).sort((left, right) =>
        left.id.localeCompare(right.id)
      ),
      views: (patch.views ?? base.views).sort((left, right) => left.id.localeCompare(right.id)),
      schemaChanges: (patch.schemaChanges ?? base.schemaChanges).sort((left, right) =>
        left.id.localeCompare(right.id)
      )
    };
  }

  private assertModelsAllowed(
    payload: ModelingGraphPayload,
    allowedTables: string[],
    workspaceId: string,
    datasourceId: string
  ): void {
    const allowed = new Set(allowedTables.map((item) => item.toLowerCase()));
    const forbiddenTables = payload.models
      .map((item) => item.tableName.toLowerCase())
      .filter((tableName) => !allowed.has(tableName));
    if (forbiddenTables.length === 0) {
      return;
    }
    throw new DomainError(
      "WORKSPACE_MODELING_GRAPH_MODEL_FORBIDDEN",
      "modeling graph 包含未授权数据表。",
      403,
      {
        workspaceId,
        datasourceId,
        forbiddenTables: Array.from(new Set(forbiddenTables)).sort((left, right) =>
          left.localeCompare(right)
        )
      }
    );
  }

  private extractEdgesFromModelingPayload(
    payload: ModelingGraphPayload
  ): Array<{
    id: string;
    name?: string;
    bridge: {
      left: {
        dataset: string;
        table: string;
        column: string;
      };
      right: {
        dataset: string;
        table: string;
        column: string;
      };
      operator: "eq";
      confidence: number;
    };
  }> {
    return payload.relationships
      .filter((item) => item.bridge.operator === "eq")
      .map((item) => ({
        id: item.id,
        name: item.name,
        bridge: {
          left: {
            dataset: item.bridge.left.dataset,
            table: item.bridge.left.table.toLowerCase(),
            column: item.bridge.left.column.toLowerCase()
          },
          right: {
            dataset: item.bridge.right.dataset,
            table: item.bridge.right.table.toLowerCase(),
            column: item.bridge.right.column.toLowerCase()
          },
          operator: "eq" as const,
          confidence: Number(item.bridge.confidence.toFixed(4))
        }
      }));
  }

  private normalizeModel(input: Record<string, unknown>): ModelingGraphPayload["models"][number] {
    const tableName = this.requireStringField(input, "tableName").toLowerCase();
    const id = this.readStringValue(input.id) ?? tableName;
    const modelName = this.readStringValue(input.modelName) ?? this.toModelName(tableName);
    const displayName = this.readNullableStringValue(input.displayName);
    const description = this.readNullableStringValue(input.description);
    const position = this.readNodePosition(input.position);
    const columnsRaw = Array.isArray(input.columns) ? input.columns : [];
    const columns = columnsRaw
      .map((item) => this.normalizeColumn(item))
      .sort((left, right) => left.name.localeCompare(right.name));
    return {
      id,
      tableName,
      modelName,
      displayName,
      description,
      position,
      columns
    };
  }

  private normalizeColumn(input: unknown): ModelingGraphPayload["models"][number]["columns"][number] {
    const record = this.asRecord(input);
    const name = this.requireStringField(record, "name").toLowerCase();
    const dataType = (this.readStringValue(record.dataType) ?? "unknown").toLowerCase();
    return {
      name,
      dataType,
      isNullable: this.readBooleanOrDefault(record.isNullable, true),
      isPrimaryKey: this.readBooleanOrDefault(record.isPrimaryKey, false),
      displayName: this.readNullableStringValue(record.displayName),
      description: this.readNullableStringValue(record.description)
    };
  }

  private normalizeRelationship(
    input: Record<string, unknown>,
    datasourceId: string
  ): ModelingGraphPayload["relationships"][number] {
    const id = this.requireStringField(input, "id");
    const name = this.readStringValue(input.name);
    const sourceRaw = this.readStringValue(input.source);
    const source: ModelingGraphPayload["relationships"][number]["source"] =
      sourceRaw === "inferred" || sourceRaw === "fk" || sourceRaw === "semantic"
        ? sourceRaw
        : "manual";
    const relationshipType = this.normalizeRelationshipType(
      this.readStringValue(input.type) ?? this.readStringValue(input.cardinality)
    );
    const bridge = this.normalizeRelationshipBridge(input.bridge, datasourceId);
    const confidence = this.readNumberOrDefault(input.confidence, bridge.confidence);
    return {
      id,
      name,
      source,
      confidence: Number(Math.max(0, Math.min(1, confidence)).toFixed(4)),
      ...(relationshipType
        ? {
            type: relationshipType,
            cardinality: relationshipType
          }
        : {}),
      bridge
    };
  }

  private normalizeRelationshipType(
    value: string | undefined
  ): ModelingGraphPayload["relationships"][number]["type"] {
    if (value === "many-to-one" || value === "one-to-many" || value === "one-to-one") {
      return value;
    }
    return undefined;
  }

  private normalizeRelationshipBridge(
    value: unknown,
    datasourceId: string
  ): ModelingGraphPayload["relationships"][number]["bridge"] {
    const record = this.asRecord(value);
    const left = this.normalizeBridgeEndpoint(record.left, datasourceId);
    const right = this.normalizeBridgeEndpoint(record.right, datasourceId);
    const operatorRaw = this.readStringValue(record.operator);
    const operator = operatorRaw === "eq" ? "eq" : "eq";
    const confidence = Number(
      Math.max(0, Math.min(1, this.readNumberOrDefault(record.confidence, 1))).toFixed(4)
    );
    return {
      left,
      right,
      operator,
      confidence
    };
  }

  private normalizeBridgeEndpoint(
    value: unknown,
    datasourceId: string
  ): ModelingGraphPayload["relationships"][number]["bridge"]["left"] {
    const record = this.asRecord(value);
    return {
      dataset: this.readStringValue(record.dataset) ?? datasourceId,
      table: this.requireStringField(record, "table").toLowerCase(),
      column: this.requireStringField(record, "column").toLowerCase()
    };
  }

  private normalizeCalculatedField(
    input: Record<string, unknown>
  ): ModelingGraphPayload["calculatedFields"][number] {
    return {
      id: this.requireStringField(input, "id"),
      modelId: this.requireStringField(input, "modelId"),
      name: this.requireStringField(input, "name"),
      expression: this.requireStringField(input, "expression"),
      dataType: this.requireStringField(input, "dataType")
    };
  }

  private normalizeView(input: Record<string, unknown>): ModelingGraphPayload["views"][number] {
    const name = this.requireStringField(input, "name");
    return {
      id: this.readStringValue(input.id) ?? name,
      name,
      sql: this.requireStringField(input, "sql"),
      displayName: this.readNullableStringValue(input.displayName),
      description: this.readNullableStringValue(input.description),
      position: this.readNodePosition(input.position)
    };
  }

  private normalizeSchemaChange(
    input: Record<string, unknown>
  ): ModelingGraphPayload["schemaChanges"][number] {
    const statusRaw = this.readStringValue(input.status);
    const kindRaw = this.readStringValue(input.kind);
    return {
      id: this.requireStringField(input, "id"),
      status: statusRaw === "resolved" ? "resolved" : "detected",
      kind:
        kindRaw === "deleted_table" ||
        kindRaw === "deleted_column" ||
        kindRaw === "modified_column_type"
          ? kindRaw
          : "other",
      summary: this.requireStringField(input, "summary")
    };
  }

  private asRecord(value: unknown): Record<string, unknown> {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      throw new DomainError("WORKSPACE_MODELING_GRAPH_INVALID", "modeling graph payload 非法。", 400);
    }
    return value as Record<string, unknown>;
  }

  private requireStringField(record: Record<string, unknown>, field: string): string {
    const normalized = this.readStringValue(record[field]);
    if (normalized) {
      return normalized;
    }
    throw new DomainError("WORKSPACE_MODELING_GRAPH_INVALID", `${field} 不能为空。`, 400, {
      field
    });
  }

  private readStringValue(value: unknown): string | undefined {
    if (typeof value !== "string") {
      return undefined;
    }
    const normalized = value.trim();
    return normalized.length > 0 ? normalized : undefined;
  }

  private readNullableStringValue(value: unknown): string | null | undefined {
    if (value === null) {
      return null;
    }
    return this.readStringValue(value);
  }

  private readNodePosition(value: unknown): { x: number; y: number } | undefined {
    if (value === undefined || value === null) {
      return undefined;
    }
    const record = this.asRecord(value);
    return {
      x: this.requireFiniteNumberField(record, "x", "position.x"),
      y: this.requireFiniteNumberField(record, "y", "position.y")
    };
  }

  private requireFiniteNumberField(
    record: Record<string, unknown>,
    key: string,
    field: string
  ): number {
    const raw = record[key];
    if (typeof raw === "number" && Number.isFinite(raw)) {
      return raw;
    }
    if (typeof raw === "string" && raw.trim().length > 0) {
      const parsed = Number(raw);
      if (Number.isFinite(parsed)) {
        return parsed;
      }
    }
    throw new DomainError("WORKSPACE_MODELING_GRAPH_INVALID", `${field} 必须是有限数值。`, 400, {
      field
    });
  }

  private readBooleanOrDefault(value: unknown, fallback: boolean): boolean {
    if (typeof value === "boolean") {
      return value;
    }
    if (typeof value === "number") {
      if (value === 1) {
        return true;
      }
      if (value === 0) {
        return false;
      }
    }
    if (typeof value === "string") {
      const normalized = value.trim().toLowerCase();
      if (normalized === "true" || normalized === "1" || normalized === "yes") {
        return true;
      }
      if (normalized === "false" || normalized === "0" || normalized === "no") {
        return false;
      }
    }
    return fallback;
  }

  private readNumberOrDefault(value: unknown, fallback: number): number {
    if (typeof value === "number" && Number.isFinite(value)) {
      return value;
    }
    if (typeof value === "string" && value.trim().length > 0) {
      const parsed = Number(value);
      if (Number.isFinite(parsed)) {
        return parsed;
      }
    }
    return fallback;
  }

  private buildSetupModelingGraphPayload(
    models: ModelingSetupModel[],
    relationships: ModelingRelationshipRecommendation[]
  ): ModelingGraphPayload {
    return {
      models: models
        .map((model) => ({
          id: model.id,
          tableName: model.tableName,
          modelName: model.modelName,
          columns: model.columns
            .map((column) => ({
              name: column.name,
              dataType: column.dataType,
              isNullable: column.isNullable,
              isPrimaryKey: column.isPrimaryKey
            }))
            .sort((left, right) => left.name.localeCompare(right.name))
        }))
        .sort((left, right) => left.id.localeCompare(right.id)),
      relationships: relationships
        .map((relationship) => {
          const source: ModelingGraphPayload["relationships"][number]["source"] =
            relationship.reason === "foreign_key_constraint" ? "fk" : "inferred";
          return {
            id: relationship.id,
            name: relationship.name,
            source,
            confidence: Number(relationship.confidence.toFixed(4)),
            bridge: {
              left: {
                dataset: relationship.bridge.left.dataset,
                table: relationship.bridge.left.table,
                column: relationship.bridge.left.column
              },
              right: {
                dataset: relationship.bridge.right.dataset,
                table: relationship.bridge.right.table,
                column: relationship.bridge.right.column
              },
              operator: "eq" as const,
              confidence: Number(relationship.bridge.confidence.toFixed(4))
            }
          };
        })
        .sort((left, right) => left.id.localeCompare(right.id)),
      calculatedFields: [],
      views: [],
      schemaChanges: []
    };
  }

  private async resolveSetupContext(
    actor: Actor,
    workspaceId: string,
    datasourceId: string,
    body: UpsertModelingSetupDto
  ): Promise<ModelingSetupContext> {
    const [tableResult, permissionResult] = await Promise.all([
      this.workspaceDatasourceService.listDatasourceTables(actor, workspaceId, datasourceId),
      this.workspaceDatasourceService.listDatasourceTablePermissions(
        actor,
        workspaceId,
        datasourceId
      )
    ]);

    if (
      body.policyVersion !== undefined &&
      permissionResult.policyVersion !== body.policyVersion
    ) {
      throw new DomainError(
        "WORKSPACE_DATASOURCE_POLICY_VERSION_CONFLICT",
        "policyVersion 已过期，请刷新后重试。",
        409,
        {
          workspaceId,
          datasourceId,
          expectedPolicyVersion: permissionResult.policyVersion,
          providedPolicyVersion: body.policyVersion
        }
      );
    }

    const discoveredSet = new Set(tableResult.items.map((item) => item.toLowerCase()));
    const allowedSet = new Set(
      permissionResult.tableNames.filter((tableName) => discoveredSet.has(tableName))
    );
    const selectedTables = Array.from(
      new Set(body.selectedTables.map((tableName) => normalizeTableName(tableName)))
    );
    const forbiddenTables = selectedTables.filter((tableName) => !allowedSet.has(tableName));
    if (forbiddenTables.length > 0) {
      throw new DomainError(
        "WORKSPACE_MODELING_SETUP_TABLE_FORBIDDEN",
        "选中的表包含未授权或不存在表。",
        403,
        {
          workspaceId,
          datasourceId,
          forbiddenTables
        }
      );
    }

    return {
      policyVersion: permissionResult.policyVersion,
      selectedTables: selectedTables.sort((left, right) => left.localeCompare(right))
    };
  }

  private async loadDatasourceOrThrow(datasourceId: string): Promise<Datasource> {
    const datasource = await this.datasourceRepository.getDatasourceById(datasourceId, {
      includeDeleted: true
    });
    if (!datasource || datasource.status === "deleted") {
      throw new DomainError("DATASOURCE_NOT_FOUND", "数据源不存在或已删除。", 404, {
        datasourceId
      });
    }
    return datasource;
  }

  private async introspectModels(
    datasource: Datasource,
    selectedTables: string[]
  ): Promise<ModelingSetupModel[]> {
    const models: ModelingSetupModel[] = [];
    for (const tableName of selectedTables) {
      const queryResult = await this.queryExecutorRouter.execute({
        datasource,
        sql: this.buildColumnDiscoverySql(datasource.type, tableName),
        limit: 200
      });
      const columns = queryResult.rows
        .map((row) => this.readColumnDefinition(row))
        .filter((item): item is ModelingSetupColumn => Boolean(item))
        .sort((left, right) => left.name.localeCompare(right.name));
      models.push({
        id: tableName,
        tableName,
        modelName: this.toModelName(tableName),
        columns
      });
    }
    return models.sort((left, right) => left.tableName.localeCompare(right.tableName));
  }

  private readColumnDefinition(row: Record<string, unknown>): ModelingSetupColumn | null {
    const name = this.readString(row, [
      "columnName",
      "column_name",
      "name",
      "field",
      "COLUMN_NAME"
    ]);
    if (!name) {
      return null;
    }
    const dataType =
      this.readString(row, ["dataType", "data_type", "type", "DATA_TYPE"]) ??
      "unknown";
    const isPrimaryKey =
      this.readBooleanLike(row["isPrimaryKey"]) ||
      this.readBooleanLike(row["primaryKey"]) ||
      this.readBooleanLike(row["pk"]) ||
      this.readString(row, ["columnKey", "column_key"])?.toUpperCase() === "PRI" ||
      this.readString(row, ["constraintType", "constraint_type"]) === "PRIMARY KEY";
    const isNotNullRaw = this.readBooleanLike(row["isNotNull"]);
    const isNullableRaw =
      this.readBooleanLike(row["isNullable"]) ??
      this.readBooleanLike(row["nullable"]) ??
      this.readBooleanLike(row["is_nullable"]) ??
      (isNotNullRaw === undefined ? undefined : !isNotNullRaw);
    const notNullRaw =
      this.readBooleanLike(row["notnull"]) ??
      this.readBooleanLike(row["notNull"]) ??
      this.readBooleanLike(row["not_null"]);
    const isNullable = isNullableRaw ?? !(notNullRaw ?? false);

    return {
      name: name.toLowerCase(),
      dataType: dataType.toLowerCase(),
      isNullable,
      isPrimaryKey
    };
  }

  private async discoverForeignKeyConstraints(
    datasource: Datasource,
    selectedTables: string[]
  ): Promise<ForeignKeyConstraint[]> {
    const selectedSet = new Set(selectedTables);
    if (selectedTables.length === 0) {
      return [];
    }
    if (datasource.type === "sqlite" || datasource.type === "csv" || datasource.type === "excel") {
      const constraints: ForeignKeyConstraint[] = [];
      for (const tableName of selectedTables) {
        const result = await this.queryExecutorRouter.execute({
          datasource,
          sql: `
SELECT "table" AS targetTable, "from" AS sourceColumn, COALESCE(NULLIF("to", ''), 'id') AS targetColumn
FROM pragma_foreign_key_list('${this.escapeSqlLiteral(tableName)}')
ORDER BY id, seq
          `.trim(),
          limit: 200
        });
        for (const row of result.rows) {
          const targetTable = this.readString(row, ["targetTable", "table"]);
          const sourceColumn = this.readString(row, ["sourceColumn", "from"]);
          const targetColumn = this.readString(row, ["targetColumn", "to"]);
          if (!targetTable || !sourceColumn || !targetColumn) {
            continue;
          }
          const normalizedTargetTable = normalizeTableName(targetTable);
          if (!selectedSet.has(normalizedTargetTable)) {
            continue;
          }
          constraints.push({
            sourceTable: tableName,
            sourceColumn: normalizeTableName(sourceColumn),
            targetTable: normalizedTargetTable,
            targetColumn: normalizeTableName(targetColumn)
          });
        }
      }
      return constraints.sort((left, right) =>
        `${left.sourceTable}.${left.sourceColumn}.${left.targetTable}.${left.targetColumn}`.localeCompare(
          `${right.sourceTable}.${right.sourceColumn}.${right.targetTable}.${right.targetColumn}`
        )
      );
    }

    const inClause = selectedTables
      .map((tableName) => `'${this.escapeSqlLiteral(tableName)}'`)
      .join(", ");
    const sql =
      datasource.type === "mysql"
        ? `
SELECT
  table_name AS sourceTable,
  column_name AS sourceColumn,
  referenced_table_name AS targetTable,
  referenced_column_name AS targetColumn
FROM information_schema.key_column_usage
WHERE table_schema = DATABASE()
  AND referenced_table_name IS NOT NULL
  AND table_name IN (${inClause})
  AND referenced_table_name IN (${inClause})
ORDER BY table_name, column_name, referenced_table_name, referenced_column_name
          `.trim()
        : `
SELECT
  kcu.table_name AS sourceTable,
  kcu.column_name AS sourceColumn,
  ccu.table_name AS targetTable,
  ccu.column_name AS targetColumn
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name
  AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage ccu
  ON ccu.constraint_name = tc.constraint_name
  AND ccu.table_schema = tc.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
  AND kcu.table_name IN (${inClause})
  AND ccu.table_name IN (${inClause})
ORDER BY kcu.table_name, kcu.column_name, ccu.table_name, ccu.column_name
          `.trim();
    const result = await this.queryExecutorRouter.execute({
      datasource,
      sql,
      limit: 200
    });

    return result.rows
      .map((row) => {
        const sourceTable = this.readString(row, ["sourceTable", "source_table"]);
        const sourceColumn = this.readString(row, ["sourceColumn", "source_column"]);
        const targetTable = this.readString(row, ["targetTable", "target_table"]);
        const targetColumn = this.readString(row, ["targetColumn", "target_column"]);
        if (!sourceTable || !sourceColumn || !targetTable || !targetColumn) {
          return null;
        }
        const normalizedSourceTable = normalizeTableName(sourceTable);
        const normalizedTargetTable = normalizeTableName(targetTable);
        if (!selectedSet.has(normalizedSourceTable) || !selectedSet.has(normalizedTargetTable)) {
          return null;
        }
        return {
          sourceTable: normalizedSourceTable,
          sourceColumn: normalizeTableName(sourceColumn),
          targetTable: normalizedTargetTable,
          targetColumn: normalizeTableName(targetColumn)
        };
      })
      .filter((item): item is ForeignKeyConstraint => Boolean(item));
  }

  private recommendRelationships(input: {
    datasourceId: string;
    models: ModelingSetupModel[];
    constraints: ForeignKeyConstraint[];
  }): ModelingRelationshipRecommendation[] {
    const modelMap = new Map(input.models.map((item) => [item.tableName, item]));
    const recommendationMap = new Map<string, ModelingRelationshipRecommendation>();

    for (const constraint of input.constraints) {
      const source = modelMap.get(constraint.sourceTable);
      const target = modelMap.get(constraint.targetTable);
      if (!source || !target) {
        continue;
      }
      const sourceColumn = source.columns.find(
        (column) => column.name === constraint.sourceColumn
      );
      const targetColumn = target.columns.find(
        (column) => column.name === constraint.targetColumn
      );
      if (!sourceColumn || !targetColumn) {
        continue;
      }
      const recommendation = this.buildRecommendation({
        datasourceId: input.datasourceId,
        sourceTable: source.tableName,
        sourceColumn: sourceColumn.name,
        targetTable: target.tableName,
        targetColumn: targetColumn.name,
        confidence: 0.99,
        reason: "foreign_key_constraint"
      });
      recommendationMap.set(this.recommendationSignature(recommendation), recommendation);
    }

    for (const sourceModel of input.models) {
      for (const column of sourceModel.columns) {
        const sourceColumn = column.name.toLowerCase();
        if (!sourceColumn.endsWith("_id") || sourceColumn === "id") {
          continue;
        }
        const stem = sourceColumn.slice(0, -3);
        const candidates = this.candidateParentTables(stem);
        for (const candidate of candidates) {
          if (candidate === sourceModel.tableName) {
            continue;
          }
          const targetModel = modelMap.get(candidate);
          if (!targetModel) {
            continue;
          }
          const targetColumn =
            targetModel.columns.find((item) => item.name === "id") ??
            targetModel.columns.find((item) => item.isPrimaryKey);
          if (!targetColumn) {
            continue;
          }
          const confidence = candidate === stem ? 0.94 : 0.86;
          const recommendation = this.buildRecommendation({
            datasourceId: input.datasourceId,
            sourceTable: sourceModel.tableName,
            sourceColumn,
            targetTable: targetModel.tableName,
            targetColumn: targetColumn.name,
            confidence,
            reason: "fk_naming_suffix"
          });
          const signature = this.recommendationSignature(recommendation);
          const existing = recommendationMap.get(signature);
          if (!existing || existing.confidence < recommendation.confidence) {
            recommendationMap.set(signature, recommendation);
          }
          break;
        }
      }
    }

    return Array.from(recommendationMap.values()).sort((left, right) => {
      if (left.confidence !== right.confidence) {
        return right.confidence - left.confidence;
      }
      return left.id.localeCompare(right.id);
    });
  }

  private buildRecommendation(input: {
    datasourceId: string;
    sourceTable: string;
    sourceColumn: string;
    targetTable: string;
    targetColumn: string;
    confidence: number;
    reason: "foreign_key_constraint" | "fk_naming_suffix";
  }): ModelingRelationshipRecommendation {
    const signature = `${input.sourceTable}.${input.sourceColumn}->${input.targetTable}.${input.targetColumn}`;
    const id = `rel_${createHash("sha1").update(signature).digest("hex").slice(0, 16)}`;
    const normalizedConfidence = Number(Math.max(0, Math.min(1, input.confidence)).toFixed(4));
    return {
      id,
      name: `${input.sourceTable}_to_${input.targetTable}`,
      sourceTable: input.sourceTable,
      sourceColumn: input.sourceColumn,
      targetTable: input.targetTable,
      targetColumn: input.targetColumn,
      confidence: normalizedConfidence,
      reason: input.reason,
      isAutoGenerated: true,
      bridge: {
        left: {
          dataset: input.datasourceId,
          table: input.sourceTable,
          column: input.sourceColumn
        },
        right: {
          dataset: input.datasourceId,
          table: input.targetTable,
          column: input.targetColumn
        },
        operator: "eq",
        confidence: normalizedConfidence
      }
    };
  }

  private candidateParentTables(stem: string): string[] {
    const normalized = stem.trim().toLowerCase();
    if (!normalized) {
      return [];
    }
    const candidates = new Set<string>([normalized]);
    if (normalized.endsWith("ies")) {
      candidates.add(`${normalized.slice(0, -3)}y`);
    } else if (normalized.endsWith("s")) {
      candidates.add(normalized.slice(0, -1));
    } else if (normalized.endsWith("y")) {
      candidates.add(`${normalized.slice(0, -1)}ies`);
      candidates.add(`${normalized}s`);
    } else {
      candidates.add(`${normalized}s`);
    }
    return Array.from(candidates);
  }

  private recommendationSignature(item: ModelingRelationshipRecommendation): string {
    return `${item.sourceTable}.${item.sourceColumn}->${item.targetTable}.${item.targetColumn}`;
  }

  private normalizeRequiredId(value: string, field: string): string {
    const normalized = value.trim();
    if (!normalized) {
      throw new DomainError("VALIDATION_ERROR", `${field} 不能为空。`, 400, {
        field
      });
    }
    return normalized;
  }

  private buildRevisionSummary(
    draftRevision: number | undefined,
    activeRevision: number | undefined
  ): {
    draftRevision?: number;
    activeRevision?: number;
    deployState: "undeployed" | "synced";
  } {
    const deployState =
      draftRevision !== undefined && activeRevision !== undefined && draftRevision === activeRevision
        ? "synced"
        : draftRevision === undefined && activeRevision !== undefined
          ? "synced"
          : "undeployed";
    return {
      draftRevision,
      activeRevision,
      deployState
    };
  }

  private normalizeOptionalIdempotencyKey(value?: string): string | undefined {
    if (value === undefined) {
      return undefined;
    }
    const normalized = value.trim();
    if (!normalized) {
      return undefined;
    }
    if (normalized.length > MAX_IDEMPOTENCY_KEY_LENGTH) {
      throw new DomainError(
        "VALIDATION_ERROR",
        `x-idempotency-key 长度不能超过 ${MAX_IDEMPOTENCY_KEY_LENGTH}`,
        400,
        {
          field: "x-idempotency-key"
        }
      );
    }
    return normalized;
  }

  private hashCommitPayload(body: UpsertModelingSetupDto): string {
    const selectedTables = Array.from(
      new Set(body.selectedTables.map((item) => normalizeTableName(item)))
    ).sort((left, right) => left.localeCompare(right));
    const explicitSelection = body.selectedRecommendationIds !== undefined;
    const selectedRecommendationIds = Array.from(
      new Set((body.selectedRecommendationIds ?? []).map((item) => item.trim()))
    ).sort((left, right) => left.localeCompare(right));
    return createHash("sha256")
      .update(
        JSON.stringify({
          policyVersion: body.policyVersion,
          selectedTables,
          selectedRecommendationMode: explicitSelection ? "explicit" : "default",
          selectedRecommendationIds: explicitSelection ? selectedRecommendationIds : null
        })
      )
      .digest("hex");
  }

  private buildCommitIdempotencyScope(input: {
    actorId: string;
    workspaceId: string;
    datasourceId: string;
    idempotencyKey: string;
  }): string {
    return [
      input.actorId.trim(),
      input.workspaceId.trim(),
      input.datasourceId.trim(),
      "POST",
      input.idempotencyKey
    ].join("::");
  }

  private readCommitIdempotencyRecord(input: {
    scope: string;
    payloadHash: string;
  }): ModelingSetupCommitResponse | null {
    const record = this.commitIdempotencyStore.get(input.scope);
    if (!record) {
      return null;
    }
    if (record.expiresAt <= Date.now()) {
      this.commitIdempotencyStore.delete(input.scope);
      return null;
    }
    if (record.payloadHash !== input.payloadHash) {
      throw new DomainError(
        "IDEMPOTENCY_REPLAY_CONFLICT",
        "相同 x-idempotency-key 不能提交不同内容。",
        409,
        {
          scope: input.scope
        }
      );
    }
    return {
      ...record.response,
      replayed: true
    };
  }

  private pruneCommitIdempotencyStore(): void {
    const now = Date.now();
    for (const [scope, record] of this.commitIdempotencyStore.entries()) {
      if (record.expiresAt <= now) {
        this.commitIdempotencyStore.delete(scope);
      }
    }
  }

  private buildColumnDiscoverySql(type: DatasourceType, tableName: string): string {
    const escapedTableName = this.escapeSqlLiteral(tableName);
    if (type === "mysql") {
      return `
SELECT
  column_name AS columnName,
  data_type AS dataType,
  is_nullable AS isNullable,
  column_key AS columnKey
FROM information_schema.columns
WHERE table_schema = DATABASE()
  AND table_name = '${escapedTableName}'
ORDER BY ordinal_position
      `.trim();
    }
    if (type === "postgresql") {
      return `
SELECT
  c.column_name AS columnName,
  c.data_type AS dataType,
  c.is_nullable AS isNullable,
  tc.constraint_type AS constraintType
FROM information_schema.columns c
LEFT JOIN information_schema.key_column_usage kcu
  ON c.table_schema = kcu.table_schema
  AND c.table_name = kcu.table_name
  AND c.column_name = kcu.column_name
LEFT JOIN information_schema.table_constraints tc
  ON kcu.constraint_name = tc.constraint_name
  AND kcu.table_schema = tc.table_schema
WHERE c.table_schema = 'public'
  AND c.table_name = '${escapedTableName}'
ORDER BY c.ordinal_position
      `.trim();
    }
    return `
SELECT
  name AS columnName,
  type AS dataType,
  "notnull" AS isNotNull,
  pk AS pk
FROM pragma_table_info('${escapedTableName}')
ORDER BY cid
    `.trim();
  }

  private buildModelPreviewSql(type: DatasourceType, tableName: string): string {
    const qualifiedName = this.quoteQualifiedIdentifier(type, tableName);
    return `SELECT * FROM ${qualifiedName}`;
  }

  private buildViewPreviewSql(sql: string): string {
    const normalized = sql.trim().replace(/;+\s*$/g, "");
    if (!normalized) {
      throw new DomainError(
        "WORKSPACE_MODELING_PREVIEW_QUERY_FAILED",
        "view SQL 为空，无法预览。",
        400
      );
    }
    return `SELECT * FROM (${normalized}) AS modeling_view_preview`;
  }

  private quoteQualifiedIdentifier(type: DatasourceType, value: string): string {
    const quote = type === "mysql" ? "`" : "\"";
    return value
      .split(".")
      .map((segment) => `${quote}${this.escapeSqlIdentifier(segment.trim(), quote)}${quote}`)
      .join(".");
  }

  private escapeSqlIdentifier(value: string, quote: string): string {
    if (!value) {
      throw new DomainError("VALIDATION_ERROR", "标识符不能为空。", 400, {
        field: "identifier"
      });
    }
    const escapedQuote = quote === "`" ? /`/g : /"/g;
    return value.replace(escapedQuote, `${quote}${quote}`);
  }

  private readString(
    row: Record<string, unknown>,
    candidateKeys: string[]
  ): string | undefined {
    for (const key of candidateKeys) {
      const value = row[key];
      if (typeof value !== "string") {
        continue;
      }
      const normalized = value.trim();
      if (normalized) {
        return normalized;
      }
    }
    return undefined;
  }

  private readBooleanLike(value: unknown): boolean | undefined {
    if (typeof value === "boolean") {
      return value;
    }
    if (typeof value === "number") {
      if (value === 0) {
        return false;
      }
      if (value === 1) {
        return true;
      }
      return undefined;
    }
    if (typeof value !== "string") {
      return undefined;
    }
    const normalized = value.trim().toLowerCase();
    if (!normalized) {
      return undefined;
    }
    if (normalized === "true" || normalized === "yes" || normalized === "y") {
      return true;
    }
    if (normalized === "false" || normalized === "no" || normalized === "n") {
      return false;
    }
    if (normalized === "1") {
      return true;
    }
    if (normalized === "0") {
      return false;
    }
    if (normalized === "not null") {
      return true;
    }
    if (normalized === "null") {
      return false;
    }
    if (normalized === "pri" || normalized === "primary key") {
      return true;
    }
    return undefined;
  }

  private toModelName(tableName: string): string {
    return tableName
      .split(/[_\s-]+/)
      .filter((item) => item.length > 0)
      .map((item) => `${item[0]?.toUpperCase() ?? ""}${item.slice(1)}`)
      .join("");
  }

  private escapeSqlLiteral(value: string): string {
    return value.replace(/'/g, "''");
  }
}
